import React,{useCallback,useEffect,useMemo,useRef,useState}from'react'
import{clearSession,readSession,updatePreferences}from'../auth/client.js'
import{askGoodTimesConcierge,cityLabel,cityOptions,loadCanonicalEvents,loadCanonicalVenues,loadExploreTaxonomy,loadGoodTimesProfile,loadItineraries,loadSavedItems,recordProductEvent,recordTasteSignal,saveItem,todayISO,unsaveItem}from'../intelligence/client.js'
import BuildMyNightPanel from'./BuildMyNightPanel.jsx'
import{loadGoodTimesAd,trackGoodTimesAd}from'./good-times-ads.js'
import{DEFAULT_ALERT_PREFS,enqueueRadarAlert,followEntity,loadRadarState,saveRadarPreferences,unfollowEntity}from'./good-times-radar.js'
import{hardenDisplayInventory,hardenRecommendationResult}from'./good-times-media-uniqueness.js'

const NAV=[['home','⌂','Now'],['discover','◇','Discover'],['concierge','✦','Concierge'],['plans','≋','Plans'],['saved','♡','Saved']]
const INTENTS=['Tonight','This Weekend','Near Me','Date Night','Black-Owned','Live Music','Brunch','Free','Family','Late Night']
const SHAKE_MODES=[['for-you','FOR YOU','Your strongest taste match'],['surprise','SURPRISE ME','Great, but outside your usual lane'],['random','RANDOM','Quality inventory, true wildcard'],['night','SHAKE MY NIGHT','Dinner → move → late night']]
const CATEGORY_LABELS={concerts_live_music:'Concerts & Live Music',nightlife:'Nightlife',comedy_performing_arts:'Comedy & Performing Arts',festivals_major_activations:'Festivals & Major Activations',dining_culinary:'Dining & Culinary',sports_watch:'Sports & Watch',community_civic:'Community & Civic',day_parties_brunch:'Day Parties & Brunch',dating_social:'Dating & Social',wellness_fitness:'Wellness & Fitness',arts_museums_culture:'Arts & Culture',family_kids:'Family & Kids',college_alumni:'College & Alumni',vip_exclusive:'VIP & Exclusive',free_things_to_do:'Free Things To Do'}

const normalize=value=>String(value||'').toLowerCase().trim()
function fmtDate(value){if(!value)return'Date TBA';return new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function fmtTime(value){if(!value||value==='TBA')return'Time TBA';const m=String(value).match(/^(\d{1,2}):(\d{2})/);if(!m)return value;const h=Number(m[1]);return`${h%12||12}:${m[2]} ${h>=12?'PM':'AM'}`}
function daysAway(value){if(!value)return 999;return Math.round((new Date(`${value}T12:00:00`)-new Date(`${todayISO()}T12:00:00`))/86400000)}
function cat(value){return CATEGORY_LABELS[value]||String(value||'Experience').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function score(item){return Number(item?.recommendation_score??item?.good_times_score??item?.quality_score??item?.culture_score??0)||0}
function statusFor(event){const text=normalize(`${event?.ticket_status||''} ${event?.status||''}`);if(text.includes('cancel'))return'CANCELLED';if(text.includes('sold'))return'SOLD OUT';if(text.includes('fast')||event?.selling_fast)return'SELLING FAST';if(text.includes('presale'))return'PRESALE';if(event?.event_date===todayISO())return'TONIGHT';if(event?.announced_at||event?.is_new)return'NEW';return event?.is_featured?'GT PICK':'CURATED'}
function matchText(item){return normalize([item?.title,item?.name,item?.venue_name,item?.neighborhood,item?.category_key,item?.subcategory_key,item?.subcategory,item?.short_desc,...(item?.vibe_tags||[]),...(item?.search_tags||[])].filter(Boolean).join(' '))}
function AppMark(){return <span className="gt3-mark">GT</span>}
function Empty({title,body,action}){return <div className="gt3-empty"><AppMark/><h2>{title}</h2><p>{body}</p>{action}</div>}
function Rail({kicker,title,action,children}){return <section className="gt3-section"><header><div><span>{kicker}</span><h2>{title}</h2></div>{action}</header><div className="gt3-rail">{children}</div></section>}

function EventCard({event,saved,onOpen,onSave,compact=false}){
  return <article className={`gt3-card gt3-event ${compact?'compact':''}`} onClick={onOpen}>
    <div className="gt3-media">{event.image_url?<img src={event.image_url} alt="" loading="lazy"/>:<div className="gt3-fallback"><span>GT</span><small>{cat(event.category_key)}</small></div>}<div className="gt3-media-veil"/><span className={`gt3-status ${statusFor(event).toLowerCase().replaceAll(' ','-')}`}>{statusFor(event)}</span><button className={`gt3-save ${saved?'active':''}`} onClick={e=>{e.stopPropagation();onSave()}}>{saved?'SAVED':'SAVE'}</button></div>
    <div className="gt3-card-copy"><small>{cat(event.category_key)}</small><h3>{event.title}</h3><div className="gt3-meta"><span>{fmtDate(event.event_date)}</span><span>{fmtTime(event.event_time)}</span></div><p>{event.venue_name||'Location TBA'}{event.neighborhood?` · ${event.neighborhood}`:''}</p>{score(event)>0&&<em>{Math.round(score(event))}% MATCH</em>}</div>
  </article>
}
function VenueCard({venue,saved,onOpen,onSave,compact=false}){
  return <article className={`gt3-card gt3-venue ${compact?'compact':''}`} onClick={onOpen}>
    <div className="gt3-media">{venue.hero_image?<img src={venue.hero_image} alt="" loading="lazy"/>:<div className="gt3-fallback"><span>GT</span><small>{cat(venue.category_key)}</small></div>}<div className="gt3-media-veil"/>{venue.is_black_owned&&<span className="gt3-status black-owned">BLACK-OWNED</span>}<button className={`gt3-save ${saved?'active':''}`} onClick={e=>{e.stopPropagation();onSave()}}>{saved?'SAVED':'SAVE'}</button></div>
    <div className="gt3-card-copy"><small>{cat(venue.category_key)}</small><h3>{venue.name}</h3><p>{venue.short_desc||`${venue.neighborhood||cityLabel(venue.city_key)} · ${venue.price_range||'GOOD TIMES place'}`}</p><div className="gt3-meta"><span>{venue.neighborhood||cityLabel(venue.city_key)}</span>{venue.google_rating&&<span>★ {Number(venue.google_rating).toFixed(1)}</span>}{venue.price_range&&<span>{venue.price_range}</span>}</div>{score(venue)>0&&<em>{Math.round(score(venue))}% MATCH</em>}</div>
  </article>
}

function AdSlot({placement,city}){
  const[ad,setAd]=useState(null),[loaded,setLoaded]=useState(false)
  const impressed=useRef(false)
  useEffect(()=>{let active=true;setLoaded(false);loadGoodTimesAd(placement,city).then(next=>{if(active){setAd(next);setLoaded(true)}});return()=>{active=false}},[placement,city])
  useEffect(()=>{if(!ad||impressed.current)return;impressed.current=true;void trackGoodTimesAd({ad,placementKey:placement,citySlug:city,eventType:'impression'})},[ad,city,placement])
  if(!loaded)return null
  const click=()=>{if(ad)void trackGoodTimesAd({ad,placementKey:placement,citySlug:city,eventType:'click'})}
  if(!ad)return <aside className={`gt3-ad gt3-ad-${placement}`} aria-label="GOOD TIMES partner placement"><span>PARTNER PLACEMENT</span><div><strong>Put your brand where the city decides what’s next.</strong><p>Reserved GOOD TIMES advertising inventory.</p></div><a href="mailto:info@thegoodtimesworldwide.com?subject=GOOD%20TIMES%20Advertising">ADVERTISE ↗</a></aside>
  return <aside className={`gt3-ad gt3-ad-${placement}`} aria-label={`Sponsored by ${ad.advertiser_name}`}><span>SPONSORED · {ad.advertiser_name}</span>{ad.image_url&&<img src={ad.image_url} alt={ad.alt_text||''}/>}<div><strong>{ad.headline}</strong>{ad.body&&<p>{ad.body}</p>}</div>{ad.cta_url&&<a href={ad.cta_url} target="_blank" rel="noreferrer" onClick={click}>{ad.cta_text||'LEARN MORE'} ↗</a>}</aside>
}

export default function GoodTimesCommandAppV2(){
  const session=useMemo(()=>readSession(),[])
  const[profile,setProfile]=useState(null),[events,setEvents]=useState([]),[venues,setVenues]=useState([]),[taxonomy,setTaxonomy]=useState([]),[saved,setSaved]=useState([]),[plans,setPlans]=useState([])
  const[city,setCity]=useState('atlanta'),[tab,setTab]=useState('home'),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[intent,setIntent]=useState(''),[mapMode,setMapMode]=useState(false),[toast,setToast]=useState('')
  const[selectedEvent,setSelectedEvent]=useState(null),[selectedVenue,setSelectedVenue]=useState(null),[radarOpen,setRadarOpen]=useState(false),[profileOpen,setProfileOpen]=useState(false)
  const[conciergeText,setConciergeText]=useState(''),[conciergeBusy,setConciergeBusy]=useState(false),[conciergeResult,setConciergeResult]=useState(null),[conciergeMessage,setConciergeMessage]=useState('')
  const[follows,setFollows]=useState([]),[alertPrefs,setAlertPrefs]=useState(DEFAULT_ALERT_PREFS),[alerts,setAlerts]=useState([])

  useEffect(()=>{document.body.classList.add('gt-app-mode');return()=>document.body.classList.remove('gt-app-mode')},[])
  const refresh=useCallback(async(nextCity)=>{
    setLoading(true)
    const[e,v,t]=await Promise.all([loadCanonicalEvents(nextCity,{limit:500}).catch(()=>[]),loadCanonicalVenues(nextCity,{limit:500}).catch(()=>[]),loadExploreTaxonomy().catch(()=>[])])
    const hardened=hardenDisplayInventory(e||[],v||[])
    setEvents(hardened.events);setVenues(hardened.venues);setTaxonomy(t||[]);setLoading(false)
  },[])
  const refreshAccount=useCallback(async p=>{
    if(!p?.id)return
    const[s,i,r]=await Promise.all([loadSavedItems(p.id,session).catch(()=>[]),loadItineraries(session).catch(()=>[]),loadRadarState(session).catch(()=>({follows:[],preferences:DEFAULT_ALERT_PREFS,alerts:[]}))])
    setSaved(s||[]);setPlans(i||[]);setFollows(r.follows||[]);setAlertPrefs({...DEFAULT_ALERT_PREFS,...(r.preferences||{})});setAlerts(r.alerts||[])
  },[session])
  useEffect(()=>{let live=true;(async()=>{const p=await loadGoodTimesProfile(session).catch(()=>null);if(!live)return;setProfile(p);const c=p?.last_city||p?.home_city||'atlanta';setCity(c);await Promise.all([refresh(c),refreshAccount(p)])})();return()=>{live=false}},[refresh,refreshAccount,session])
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(t)},[toast])

  const savedKeys=useMemo(()=>new Set(saved.map(x=>`${x.item_type}:${x.item_id}`)),[saved])
  const followKeys=useMemo(()=>new Set(follows.filter(x=>x.is_active!==false).map(x=>`${x.entity_type}:${x.entity_id}`)),[follows])
  const today=useMemo(()=>events.filter(e=>e.event_date===todayISO()),[events])
  const week=useMemo(()=>events.filter(e=>daysAway(e.event_date)>=0&&daysAway(e.event_date)<=7),[events])
  const rankedEvents=useMemo(()=>[...events].sort((a,b)=>score(b)-score(a)||daysAway(a.event_date)-daysAway(b.event_date)),[events])
  const rankedVenues=useMemo(()=>[...venues].sort((a,b)=>score(b)-score(a)||Number(b.google_rating||0)-Number(a.google_rating||0)),[venues])
  const radar=useMemo(()=>{
    const rows=[];const tonightPick=rankedEvents.find(e=>e.event_date===todayISO());const urgent=rankedEvents.find(e=>statusFor(e)==='SELLING FAST'||statusFor(e)==='PRESALE');const upcoming=rankedEvents.find(e=>daysAway(e.event_date)>0&&daysAway(e.event_date)<=7)
    if(urgent)rows.push({label:statusFor(urgent),item:urgent});if(tonightPick&&!rows.some(r=>r.item===tonightPick))rows.push({label:'TONIGHT',item:tonightPick});if(upcoming&&!rows.some(r=>r.item===upcoming))rows.push({label:'THIS WEEK',item:upcoming});return rows.slice(0,3)
  },[rankedEvents])
  const filtered=useMemo(()=>{
    let e=[...events],v=[...venues];const q=normalize(query),i=normalize(intent)
    const predicate=item=>{const text=matchText(item);if(q&&!text.includes(q))return false;if(!i)return true;if(i==='tonight')return item.event_date===todayISO();if(i==='this weekend')return item.event_date&&daysAway(item.event_date)>=0&&daysAway(item.event_date)<=7;if(i==='black-owned')return Boolean(item.is_black_owned)||text.includes('black-owned');if(i==='live music')return /live music|concert|jazz|r&b|rnb|music/.test(text);if(i==='brunch')return /brunch|day party/.test(text);if(i==='free')return /free/.test(text);if(i==='family')return /family|kids/.test(text);if(i==='late night')return /late|nightclub|lounge|after party/.test(text);if(i==='date night')return /date|romantic|restaurant|wine|rooftop/.test(text);return true}
    return{events:e.filter(predicate),venues:v.filter(predicate)}
  },[events,venues,query,intent])
  const categories=useMemo(()=>taxonomy.filter(x=>x?.id||x?.category_key).slice(0,12),[taxonomy])

  useEffect(()=>{
    if(!session?.user?.id||!events.length||!follows.length)return
    const prefMap={NEW:'just_announced',PRESALE:'presale','SELLING FAST':'selling_fast',TONIGHT:'saved_reminders'}
    for(const follow of follows.filter(x=>x.entity_type==='event'&&x.is_active!==false)){
      const item=events.find(e=>String(e.event_key)===String(follow.entity_id));if(!item)continue
      const status=statusFor(item),pref=prefMap[status];if(!pref||alertPrefs?.[pref]===false)continue
      const alertType=status==='NEW'?'just_announced':status==='PRESALE'?'presale':status==='SELLING FAST'?'selling_fast':'saved_reminder'
      const key=`${session.user.id}:event:${item.event_key}:${status}:${item.event_date||todayISO()}`
      void enqueueRadarAlert({alertType,objectType:'event',objectId:item.event_key,citySlug:city,title:`${status}: ${item.title}`,body:`${fmtDate(item.event_date)} · ${fmtTime(item.event_time)} · ${item.venue_name||'Location TBA'}`,actionUrl:'/',dedupeKey:key,metadata:{source:'client-radar-sync'}},session)
    }
  },[alertPrefs,city,events,follows,session])

  const changeCity=async c=>{setCity(c);setQuery('');setIntent('');await refresh(c);if(session?.user?.id)await updatePreferences(session.user.id,{last_city:c},session.access_token).catch(()=>false)}
  const toggleSave=async(type,id)=>{if(!profile?.id){setToast('Sign in to save and personalize.');return}const key=`${type}:${id}`,exists=savedKeys.has(key);try{if(exists){await unsaveItem({profileId:profile.id,itemType:type,itemId:id},session);setSaved(x=>x.filter(row=>`${row.item_type}:${row.item_id}`!==key));setToast('Removed from Saved.')}else{await saveItem({profileId:profile.id,itemType:type,itemId:id},session);setSaved(await loadSavedItems(profile.id,session));setToast('Saved. GOOD TIMES will learn from this.')}}catch(e){setToast(e.message||'Could not save.') }}
  const toggleFollow=async(type,item)=>{if(!session?.user?.id){setToast('Sign in to follow and get Radar alerts.');return}const id=type==='event'?item.event_key:item.id,key=`${type}:${id}`,exists=followKeys.has(key);try{if(exists){await unfollowEntity({entityType:type,entityId:id},session);setFollows(rows=>rows.filter(r=>`${r.entity_type}:${r.entity_id}`!==key));setToast('Radar stopped watching this.')}else{const row=await followEntity({entityType:type,entityId:id,citySlug:city,alertLevel:alertPrefs.intensity||'normal',metadata:{name:item.title||item.name,venue_name:item.venue_name||null}},session);if(row)setFollows(rows=>[row,...rows.filter(r=>`${r.entity_type}:${r.entity_id}`!==key)]);setToast('Following. Radar is watching it.')}}catch(e){setToast(e.message||'Could not update Follow.') }}
  const updatePrefs=async patch=>{const next={...alertPrefs,...patch};setAlertPrefs(next);try{const savedPrefs=await saveRadarPreferences(next,session);setAlertPrefs({...DEFAULT_ALERT_PREFS,...savedPrefs});setToast('Radar settings saved.')}catch(e){setToast(e.message||'Could not save Radar settings.')}}
  const openEvent=e=>{setSelectedEvent(e);recordProductEvent({eventName:'event_opened',surface:tab,objectType:'event',objectId:e.event_key,city},session);recordTasteSignal({entityType:'event',entityId:e.event_key,signalType:'view',city},session)}
  const openVenue=v=>{setSelectedVenue(v);recordProductEvent({eventName:'venue_opened',surface:tab,objectType:'venue',objectId:v.id,city},session);recordTasteSignal({entityType:'venue',entityId:v.id,signalType:'view',city},session)}
  const runConcierge=async(text=conciergeText,action='recommend')=>{const clean=String(text||'').trim();if(!clean||conciergeBusy)return;setConciergeBusy(true);setConciergeMessage('');try{const raw=await askGoodTimesConcierge({query:clean,action,city},session);const result=hardenRecommendationResult(raw);setConciergeResult(result);setConciergeMessage(result?.message||'Here are the strongest current options.');if(result?.itinerary){setPlans(p=>[result.itinerary,...p.filter(x=>x.id!==result.itinerary.id)]);setToast('Plan built and saved.')}}catch(e){setConciergeMessage(e.message||'I could not verify a strong answer from current data.')}finally{setConciergeBusy(false)}}
  const shake=async mode=>{if(mode==='random'){const pool=rankedVenues.filter(v=>Number(v.quality_score||0)>=70||Number(v.google_rating||0)>=4.2),source=pool.length?pool:rankedVenues,pick=source[Math.floor(Math.random()*Math.max(1,source.length))];if(pick){setSelectedVenue(pick);recordTasteSignal({entityType:'venue',entityId:pick.id,signalType:'shake_random',city},session)}return}const prompts={'for-you':`Pick the single strongest place for me in ${cityLabel(city)} right now based on my taste and current verified inventory. Explain why.`,surprise:`Surprise me with a high-quality ${cityLabel(city)} experience outside my usual habits, using current verified inventory.`,night:`Build my complete night in ${cityLabel(city)} using current events and verified places. Keep travel logical and include a strong opening move, main move and optional late-night move.`};setConciergeText(prompts[mode]);await runConcierge(prompts[mode],mode==='night'?'itinerary':'recommend')}

  if(loading&&!events.length&&!venues.length)return <div className="gt3-loading"><AppMark/><span>Reading the city…</span></div>
  return <div className="gt3-app">
    <header className="gt3-topbar"><button className="gt3-brand" onClick={()=>setTab('home')}><AppMark/><span><strong>GOOD TIMES</strong><small>WORLDWIDE EXPERIENCE CONCIERGE</small></span></button><div className="gt3-top-actions"><button className="gt3-city" onClick={()=>setProfileOpen(true)}>⌖ {cityLabel(city)}</button><button className="gt3-account" onClick={()=>setProfileOpen(true)} aria-label="Open profile">◎</button></div></header>
    <div className="gt3-radar"><button onClick={()=>setRadarOpen(v=>!v)}><span><i/> CITY RADAR</span><strong>{radar[0]?`${radar[0].label}: ${radar[0].item.title}`:`${follows.length} followed · ${alerts.length} alerts`}</strong><em>{radar.length||alerts.length||follows.length} signals ›</em></button>{radarOpen&&<div className="gt3-radar-drawer"><header><div><small>GOOD TIMES RADAR</small><strong>Watch what matters before it becomes obvious.</strong></div><span>{follows.length} followed</span></header>{radar.map(r=><button key={`${r.label}-${r.item.event_key}`} onClick={()=>{setRadarOpen(false);openEvent(r.item)}}><small>{r.label}</small><strong>{r.item.title}</strong><span>{fmtDate(r.item.event_date)} · {fmtTime(r.item.event_time)} · {r.item.venue_name||'TBA'}</span></button>)}{alerts.slice(0,5).map(a=><div className="gt3-radar-alert" key={a.id}><small>{String(a.alert_type||'alert').replaceAll('_',' ')}</small><strong>{a.title}</strong><span>{a.body}</span></div>)}<section className="gt3-radar-settings"><label>ALERT INTENSITY<select value={alertPrefs.intensity||'normal'} onChange={e=>updatePrefs({intensity:e.target.value})}><option value="quiet">Quiet</option><option value="normal">Normal</option><option value="never_miss">Never Miss</option></select></label>{[['just_announced','Just announced'],['presale','Presales'],['selling_fast','Selling fast'],['weekend_brief','Weekend brief']].map(([key,label])=><label className="switch" key={key}><span>{label}</span><input type="checkbox" checked={alertPrefs[key]!==false} onChange={e=>updatePrefs({[key]:e.target.checked})}/></label>)}</section></div>}</div>

    <main className="gt3-main">
      {tab==='home'&&<>
        <section className="gt3-home-intro"><div><span>GOOD TIMES · {cityLabel(city).toUpperCase()}</span><h1>Know before<br/>everybody knows.</h1><p>What matters, what is coming, and your best next move—ranked from current city inventory.</p></div><div className="gt3-ask"><label>ASK GOOD TIMES</label><div><input value={conciergeText} onChange={e=>setConciergeText(e.target.value)} placeholder="What are you trying to do?" onKeyDown={e=>{if(e.key==='Enter'){setTab('concierge');runConcierge(conciergeText,'recommend')}}}/><button onClick={()=>{setTab('concierge');runConcierge(conciergeText,'recommend')}}>ASK ✦</button></div><div>{['What matters tonight?','Build my night','Something different','Black-owned date night'].map(p=><button key={p} onClick={()=>{setConciergeText(p);setTab('concierge');runConcierge(p,p==='Build my night'?'itinerary':'recommend')}}>{p}</button>)}</div></div></section>
        <AdSlot placement="home_radar_strip" city={city}/>
        <section className="gt3-the5"><header><div><span>YOUR SHORTLIST</span><h2>The 5.</h2></div><p>Five strong things worth your attention instead of 120 things to sort through.</p></header><div className="gt3-five-grid">{rankedEvents.slice(0,5).map((e,i)=><button key={e.event_key} onClick={()=>openEvent(e)}><b>0{i+1}</b><span><small>{statusFor(e)}</small><strong>{e.title}</strong><em>{fmtDate(e.event_date)} · {e.venue_name||'TBA'}</em></span></button>)}</div></section>
        <AdSlot placement="home_feed_1" city={city}/>
        <Rail kicker="RIGHT NOW" title={today.length?'Happening today':'Next up'} action={<button onClick={()=>{setTab('discover');setIntent('Tonight')}}>See all</button>}>{(today.length?today:rankedEvents).slice(0,10).map(e=><EventCard compact key={e.event_key} event={e} saved={savedKeys.has(`event:${e.event_key}`)} onOpen={()=>openEvent(e)} onSave={()=>toggleSave('event',e.event_key)}/>)}</Rail>
        <Rail kicker="FOR YOU" title="Ranked to your taste" action={<button onClick={()=>setTab('concierge')}>Refine ✦</button>}>{rankedVenues.slice(0,10).map(v=><VenueCard compact key={v.id} venue={v} saved={savedKeys.has(`venue:${v.id}`)} onOpen={()=>openVenue(v)} onSave={()=>toggleSave('venue',v.id)}/>)}</Rail>
        <Rail kicker="NEXT SEVEN DAYS" title="Worth planning around" action={<button onClick={()=>{setTab('discover');setIntent('This Weekend')}}>See week</button>}>{week.slice(0,10).map(e=><EventCard compact key={e.event_key} event={e} saved={savedKeys.has(`event:${e.event_key}`)} onOpen={()=>openEvent(e)} onSave={()=>toggleSave('event',e.event_key)}/>)}</Rail>
      </>}

      {tab==='discover'&&<section className="gt3-screen"><div className="gt3-screen-head"><span>DISCOVER</span><h1>Find the move, not the category.</h1><p>Search by venue, neighborhood, vibe, occasion, ownership, or what you actually feel like doing.</p></div><div className="gt3-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try: grown R&B in Midtown…"/><button onClick={()=>setMapMode(v=>!v)}>{mapMode?'LIST':'MAP'}</button></div><div className="gt3-intents">{INTENTS.map(i=><button className={intent===i?'active':''} onClick={()=>setIntent(intent===i?'':i)} key={i}>{i}</button>)}</div><AdSlot placement="discover_inline" city={city}/>{mapMode?<div className="gt3-map"><iframe title={`${cityLabel(city)} map`} src={`https://www.openstreetmap.org/export/embed.html?bbox=${encodeURIComponent(city==='atlanta'?'-84.62,33.60,-84.15,34.02':'-180,-85,180,85')}&layer=mapnik`}/><div><strong>{filtered.venues.length} matching places</strong><p>Use list mode for ranked details.</p>{filtered.venues.slice(0,6).map(v=><button key={v.id} onClick={()=>openVenue(v)}>{v.name}<span>{v.neighborhood||cityLabel(city)}</span></button>)}</div></div>:<><div className="gt3-discover-split"><div><span>EVENTS</span><strong>{filtered.events.length}</strong></div><div><span>PLACES</span><strong>{filtered.venues.length}</strong></div><div><span>FILTER</span><strong>{intent||'Everything'}</strong></div></div>{filtered.events.length>0&&<Rail kicker="EVENTS" title={query||intent||'Current experiences'}>{filtered.events.slice(0,18).map(e=><EventCard compact key={e.event_key} event={e} saved={savedKeys.has(`event:${e.event_key}`)} onOpen={()=>openEvent(e)} onSave={()=>toggleSave('event',e.event_key)}/>)}</Rail>}<Rail kicker="PLACES" title="Strong places for this search">{filtered.venues.slice(0,18).map(v=><VenueCard compact key={v.id} venue={v} saved={savedKeys.has(`venue:${v.id}`)} onOpen={()=>openVenue(v)} onSave={()=>toggleSave('venue',v.id)}/>)}</Rail><section className="gt3-category-index"><header><span>BROWSE THE DATABASE</span><h2>Categories, when you want them.</h2></header><div>{categories.map(c=><button key={c.id||c.category_key} onClick={()=>{setQuery(c.name||cat(c.id||c.category_key));setIntent('')}}><strong>{c.name||cat(c.id||c.category_key)}</strong><span>Explore ›</span></button>)}</div></section></>}</section>}

      {tab==='concierge'&&<section className="gt3-screen"><div className="gt3-concierge-hero"><div><span>GOOD TIMES CONCIERGE</span><h1>Tell us the night.<br/>We make the decisions.</h1><p>Natural-language recommendations first. Guided controls only when you want to fine-tune.</p></div><AppMark/></div><div className="gt3-concierge-box"><textarea value={conciergeText} onChange={e=>setConciergeText(e.target.value)} placeholder="Example: date night tonight, upscale dinner, then R&B, under $250 for two…"/><div><button onClick={()=>runConcierge(conciergeText,'recommend')} disabled={conciergeBusy}>Recommend</button><button className="primary" onClick={()=>runConcierge(conciergeText,'itinerary')} disabled={conciergeBusy}>Build my night ✦</button></div>{conciergeBusy&&<p className="gt3-thinking">Checking current inventory, fit, timing and quality…</p>}{conciergeMessage&&<p className="gt3-answer">{conciergeMessage}</p>}</div><AdSlot placement="concierge_inline" city={city}/><section className="gt3-shake"><header><div><span>GOOD TIMES SHAKE</span><h2>Don't want to decide?</h2></div><p>Choose how random you actually want us to be.</p></header><div>{SHAKE_MODES.map(([id,title,body])=><button key={id} onClick={()=>shake(id)}><span>✦</span><strong>{title}</strong><small>{body}</small></button>)}</div></section>{conciergeResult?.events?.length>0&&<Rail kicker="CONCIERGE PICKS" title="Events that fit">{conciergeResult.events.slice(0,10).map(e=><EventCard compact key={e.event_key} event={e} saved={savedKeys.has(`event:${e.event_key}`)} onOpen={()=>openEvent(e)} onSave={()=>toggleSave('event',e.event_key)}/>)}</Rail>}{conciergeResult?.venues?.length>0&&<Rail kicker="CONCIERGE PICKS" title="Places that fit">{conciergeResult.venues.slice(0,10).map(v=><VenueCard compact key={v.id} venue={v} saved={savedKeys.has(`venue:${v.id}`)} onOpen={()=>openVenue(v)} onSave={()=>toggleSave('venue',v.id)}/>)}</Rail>}<details className="gt3-fine-tune"><summary>Fine-tune with the guided builder</summary><BuildMyNightPanel cityName={cityLabel(city)} busy={conciergeBusy} onBuild={prompt=>{setConciergeText(prompt);runConcierge(prompt,'itinerary')}}/></details></section>}

      {tab==='plans'&&<section className="gt3-screen"><div className="gt3-screen-head"><span>PLANS</span><h1>Your nights, operational.</h1><p>Every itinerary should answer where, when, what is next, and how to act.</p></div>{plans.length===0?<Empty title="No plans yet" body="Tell the Concierge what you want and GOOD TIMES will build the route." action={<button className="gt3-primary" onClick={()=>setTab('concierge')}>Build my first plan</button>}/>:<div className="gt3-plans">{plans.map(p=><article key={p.id}><header><span>{String(p.status||'draft').toUpperCase()}</span><h2>{p.name||'GOOD TIMES plan'}</h2><p>{fmtDate(p.itinerary_date)} · {cityLabel(p.city_id||city)} · {p.group_size||1} guests</p></header><div>{(p.stops||[]).map((s,i)=><section key={`${s.id}-${i}`}><b>{String(i+1).padStart(2,'0')}</b><span><small>{s.role||s.type||'STOP'}</small><strong>{s.name}</strong><em>{s.time?fmtTime(s.time):'Time flexible'} · {s.venue||s.address||''}</em></span>{s.ticket_url&&<a href={s.ticket_url} target="_blank" rel="noreferrer">Tickets</a>}{s.booking_link&&<a href={s.booking_link} target="_blank" rel="noreferrer">Book</a>}</section>)}</div></article>)}</div>}</section>}

      {tab==='saved'&&<section className="gt3-screen"><div className="gt3-screen-head"><span>SAVED + FOLLOWING</span><h1>Your memory for the city.</h1><p>{saved.length} saved · {follows.length} followed. Radar watches followed things for changes.</p></div><AdSlot placement="saved_partner" city={city}/>{saved.length===0&&follows.length===0?<Empty title="Nothing saved or followed yet" body="Save something for memory. Follow something when you want Radar to watch it." action={<button className="gt3-primary" onClick={()=>setTab('discover')}>Explore the city</button>}/>:<><Rail kicker="SAVED EVENTS" title={`${events.filter(e=>savedKeys.has(`event:${e.event_key}`)).length} experiences`}>{events.filter(e=>savedKeys.has(`event:${e.event_key}`)).map(e=><EventCard compact key={e.event_key} event={e} saved onOpen={()=>openEvent(e)} onSave={()=>toggleSave('event',e.event_key)}/>)}</Rail><Rail kicker="SAVED PLACES" title={`${venues.filter(v=>savedKeys.has(`venue:${v.id}`)).length} places`}>{venues.filter(v=>savedKeys.has(`venue:${v.id}`)).map(v=><VenueCard compact key={v.id} venue={v} saved onOpen={()=>openVenue(v)} onSave={()=>toggleSave('venue',v.id)}/>)}</Rail><section className="gt3-following"><span>RADAR WATCHLIST</span>{follows.map(f=><div key={`${f.entity_type}:${f.entity_id}`}><strong>{f.metadata?.name||`${f.entity_type}: ${f.entity_id}`}</strong><small>{f.alert_level||'normal'} alerts · {f.city_slug||'all cities'}</small></div>)}</section></>}</section>}
    </main>

    <nav className="gt3-mobile-nav">{NAV.map(([id,icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);document.querySelector('.gt3-main')?.scrollTo?.({top:0,behavior:'instant'})}}><span>{icon}</span><small>{label}</small></button>)}</nav>

    {selectedEvent&&<div className="gt3-modal-bg" onMouseDown={()=>setSelectedEvent(null)}><article className="gt3-detail" onMouseDown={e=>e.stopPropagation()}><button className="gt3-close" onClick={()=>setSelectedEvent(null)}>×</button>{selectedEvent.image_url?<img src={selectedEvent.image_url} alt=""/>:<div className="gt3-detail-fallback"><AppMark/></div>}<div><span>{statusFor(selectedEvent)} · {cat(selectedEvent.category_key)}</span><h2>{selectedEvent.title}</h2><p>{fmtDate(selectedEvent.event_date)} · {fmtTime(selectedEvent.event_time)} · {selectedEvent.venue_name||'TBA'}</p><section><strong>GOOD TIMES TAKE</strong><p>{selectedEvent.reasons?.[0]||'This made the current city shortlist based on timing, quality and available recommendation signals.'}</p></section><div className="gt3-detail-actions"><button onClick={()=>toggleSave('event',selectedEvent.event_key)}>{savedKeys.has(`event:${selectedEvent.event_key}`)?'Saved':'Save'}</button><button className={followKeys.has(`event:${selectedEvent.event_key}`)?'followed':''} onClick={()=>toggleFollow('event',selectedEvent)}>{followKeys.has(`event:${selectedEvent.event_key}`)?'Following ✓':'Follow + alerts'}</button>{selectedEvent.ticket_url&&<a href={selectedEvent.ticket_url} target="_blank" rel="noreferrer">Tickets</a>}<button className="primary" onClick={()=>{const p=`Build my night around ${selectedEvent.title} at ${selectedEvent.venue_name||'this venue'} on ${fmtDate(selectedEvent.event_date)}.`;setSelectedEvent(null);setTab('concierge');setConciergeText(p);runConcierge(p,'itinerary')}}>Plan around this ✦</button></div></div></article></div>}
    {selectedVenue&&<div className="gt3-modal-bg" onMouseDown={()=>setSelectedVenue(null)}><article className="gt3-detail" onMouseDown={e=>e.stopPropagation()}><button className="gt3-close" onClick={()=>setSelectedVenue(null)}>×</button>{selectedVenue.hero_image?<img src={selectedVenue.hero_image} alt=""/>:<div className="gt3-detail-fallback"><AppMark/></div>}<div><span>{cat(selectedVenue.category_key)} · {selectedVenue.neighborhood||cityLabel(city)}</span><h2>{selectedVenue.name}</h2><p>{selectedVenue.short_desc||selectedVenue.insider_tip||'Verified GOOD TIMES place.'}</p><section><strong>KNOW BEFORE YOU GO</strong><p>{[selectedVenue.price_range,selectedVenue.dress_code,selectedVenue.reservation_req,selectedVenue.hours_summary].filter(Boolean).join(' · ')||'Confirm current hours and entry details before heading out.'}</p></section><div className="gt3-detail-actions"><button onClick={()=>toggleSave('venue',selectedVenue.id)}>{savedKeys.has(`venue:${selectedVenue.id}`)?'Saved':'Save'}</button><button className={followKeys.has(`venue:${selectedVenue.id}`)?'followed':''} onClick={()=>toggleFollow('venue',selectedVenue)}>{followKeys.has(`venue:${selectedVenue.id}`)?'Following ✓':'Follow + alerts'}</button>{selectedVenue.booking_link&&<a href={selectedVenue.booking_link} target="_blank" rel="noreferrer">Book</a>}<button className="primary" onClick={()=>{const p=`Plan a complete night that includes ${selectedVenue.name} in ${selectedVenue.neighborhood||cityLabel(city)}.`;setSelectedVenue(null);setTab('concierge');setConciergeText(p);runConcierge(p,'itinerary')}}>Plan a night here ✦</button></div></div></article></div>}
    {profileOpen&&<div className="gt3-modal-bg" onMouseDown={()=>setProfileOpen(false)}><aside className="gt3-profile" onMouseDown={e=>e.stopPropagation()}><button className="gt3-close" onClick={()=>setProfileOpen(false)}>×</button><AppMark/><span>YOUR GOOD TIMES</span><h2>{profile?.full_name||session?.user?.email||'Guest'}</h2><p>{session?.user?.email||'Browse freely. Sign in when you want to save, follow and personalize.'}</p><label>HOME CITY<select value={city} onChange={e=>changeCity(e.target.value)}>{cityOptions.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><div className="gt3-profile-stats"><div><strong>{profile?.vibe_preferences?.length||0}</strong><span>Preferences</span></div><div><strong>{saved.length}</strong><span>Saved</span></div><div><strong>{follows.length}</strong><span>Following</span></div></div><button onClick={()=>{setProfileOpen(false);setRadarOpen(true)}}>Open Radar + alert settings</button>{session&&<button className="danger" onClick={()=>{clearSession();window.location.reload()}}>Sign out</button>}</aside></div>}
    {toast&&<div className="gt3-toast">{toast}</div>}
  </div>
}
