import React,{useCallback,useEffect,useMemo,useState}from'react'
import{clearSession,readSession,updatePreferences}from'../auth/client.js'
import{askGoodTimesConcierge,cityLabel,cityOptions,loadCanonicalEvents,loadCanonicalVenues,loadExploreTaxonomy,loadGoodTimesProfile,loadItineraries,loadSavedItems,recordProductEvent,recordTasteSignal,saveItem,todayISO,unsaveItem}from'../intelligence/client.js'
import BuildMyNightPanel from'./BuildMyNightPanel.jsx'
import ExploreTaxonomyBrowser from'./ExploreTaxonomyBrowser.jsx'
import{loadGoodTimesAd,trackGoodTimesAd}from'./good-times-ads.js'
import{DEFAULT_ALERT_PREFS,enqueueRadarAlert,followEntity,loadRadarState,saveRadarPreferences,unfollowEntity}from'./good-times-radar.js'
import{hardenDisplayInventory,hardenRecommendationResult}from'./good-times-media-uniqueness.js'

const NAV=[['home','⌂','Now'],['discover','◇','Discover'],['concierge','✦','Concierge'],['radar','◉','Radar'],['vault','▣','Vault']]
const INTENTS=['Tonight','This Weekend','Date Night','Black-Owned','Live Music','Brunch','Free','Family','Late Night']
const SHAKE_MODES=[['for-you','FOR YOU','Your strongest taste match'],['surprise','SURPRISE ME','Something great outside your normal lane'],['random','RANDOM','A quality wildcard'],['night','SHAKE MY NIGHT','A complete night, built for you']]
const CATEGORY_LABELS={concerts_live_music:'Concerts & Live Music',nightlife:'Nightlife',comedy_performing_arts:'Comedy & Performing Arts',festivals_major_activations:'Festivals & Major Activations',dining_culinary:'Dining & Culinary',sports_watch:'Sports & Watch',community_civic:'Community & Civic',day_parties_brunch:'Day Parties & Brunch',dating_social:'Dating & Social',wellness_fitness:'Wellness & Fitness',arts_museums_culture:'Arts & Culture',family_kids:'Family & Kids',college_alumni:'College & Alumni',vip_exclusive:'VIP & Exclusive',free_things_to_do:'Free Things To Do'}
const GENERIC_MEDIA=/images\.unsplash\.com|\/good-times-backgrounds\/(?:gt-cat-|event-)/i
const HOME_EXCLUDED_PLACE_TYPES=/housing|hotel|lodging|staycation|travel/

const normalize=value=>String(value||'').toLowerCase().trim()
function fmtDate(value){if(!value)return'Date TBA';return new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function fmtTime(value){if(!value||value==='TBA')return'Time TBA';const m=String(value).match(/^(\d{1,2}):(\d{2})/);if(!m)return value;const h=Number(m[1]);return`${h%12||12}:${m[2]} ${h>=12?'PM':'AM'}`}
function daysAway(value){if(!value)return 999;return Math.round((new Date(`${value}T12:00:00`)-new Date(`${todayISO()}T12:00:00`))/86400000)}
function cat(value){return CATEGORY_LABELS[value]||String(value||'Experience').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function score(item){return Number(item?.recommendation_score??item?.good_times_score??item?.quality_score??item?.culture_score??0)||0}
function statusFor(event){const text=normalize(`${event?.ticket_status||''} ${event?.status||''}`);if(text.includes('cancel'))return'CANCELLED';if(text.includes('sold'))return'SOLD OUT';if(text.includes('fast')||event?.selling_fast)return'SELLING FAST';if(text.includes('presale'))return'PRESALE';if(event?.event_date===todayISO())return'TONIGHT';if(event?.announced_at||event?.is_new)return'NEW';return event?.is_featured?'GT PICK':'CURATED'}
function matchText(item){return normalize([item?.title,item?.name,item?.venue_name,item?.neighborhood,item?.category_key,item?.subcategory_key,item?.subcategory,item?.venue_subcategory,item?.short_desc,...(item?.vibe_tags||[]),...(item?.search_tags||[])].filter(Boolean).join(' '))}
function safeMedia(value){const raw=String(value||'').trim();return raw&&!GENERIC_MEDIA.test(raw)?raw:null}
function matchesIntent(item,intent,isEvent=false){const i=normalize(intent),text=matchText(item);if(!i)return true;if(i==='tonight')return isEvent?item.event_date===todayISO():true;if(i==='this weekend')return isEvent?Boolean(item.event_date&&daysAway(item.event_date)>=0&&daysAway(item.event_date)<=7):true;if(i==='black-owned')return Boolean(item.is_black_owned)||text.includes('black-owned');if(i==='live music')return /live music|concert|jazz|r&b|rnb|music|dj/.test(text);if(i==='brunch')return /brunch|day party/.test(text);if(i==='free')return /free/.test(text);if(i==='family')return /family|kids|museum|zoo|aquarium/.test(text);if(i==='late night')return /late|nightclub|lounge|after party|bar/.test(text);if(i==='date night')return /date|romantic|restaurant|wine|rooftop|fine dining|cocktail/.test(text);return true}
function AppMark(){return <span className="gt4-mark">GT</span>}
function Empty({title,body,action}){return <div className="gt4-empty"><AppMark/><h2>{title}</h2><p>{body}</p>{action}</div>}
function Section({kicker,title,action,children}){return <section className="gt4-section"><header><div><span>{kicker}</span><h2>{title}</h2></div>{action}</header><div className="gt4-stack">{children}</div></section>}

function EventCard({event,saved,onOpen,onSave}){
  const media=safeMedia(event.image_url)
  return <article className="gt4-card gt4-event" onClick={onOpen}>
    <div className="gt4-thumb">{media?<img src={media} alt="" loading="lazy"/>:<div className="gt4-fallback"><AppMark/><small>{cat(event.category_key)}</small></div>}<span className="gt4-status">{statusFor(event)}</span></div>
    <div className="gt4-card-copy"><small>{cat(event.category_key)}</small><h3>{event.title}</h3><p>{fmtDate(event.event_date)} · {fmtTime(event.event_time)}</p><em>{event.venue_name||'Location TBA'}</em>{score(event)>0&&<b>{Math.round(score(event))}% match</b>}</div>
    <button className={`gt4-save ${saved?'active':''}`} aria-label={saved?'Remove saved item':'Save item'} onClick={e=>{e.stopPropagation();onSave()}}>{saved?'✓':'♡'}</button>
  </article>
}
function VenueCard({venue,saved,onOpen,onSave}){
  const media=safeMedia(venue.hero_image)
  return <article className="gt4-card gt4-venue" onClick={onOpen}>
    <div className="gt4-thumb">{media?<img src={media} alt="" loading="lazy"/>:<div className="gt4-fallback"><AppMark/><small>{cat(venue.category_key)}</small></div>}{venue.is_black_owned&&<span className="gt4-status black">BLACK-OWNED</span>}</div>
    <div className="gt4-card-copy"><small>{cat(venue.category_key)}</small><h3>{venue.name}</h3><p>{venue.short_desc||'GOOD TIMES verified place.'}</p><em>{[venue.neighborhood,venue.google_rating?`★ ${Number(venue.google_rating).toFixed(1)}`:null,venue.price_range].filter(Boolean).join(' · ')}</em>{score(venue)>0&&<b>{Math.round(score(venue))}% match</b>}</div>
    <button className={`gt4-save ${saved?'active':''}`} aria-label={saved?'Remove saved item':'Save item'} onClick={e=>{e.stopPropagation();onSave()}}>{saved?'✓':'♡'}</button>
  </article>
}

function AdSlot({placement,city}){
  const[ad,setAd]=useState(null),[loaded,setLoaded]=useState(false)
  useEffect(()=>{let live=true;setLoaded(false);loadGoodTimesAd(placement,city).then(next=>{if(live){setAd(next);setLoaded(true)}});return()=>{live=false}},[placement,city])
  useEffect(()=>{if(ad)void trackGoodTimesAd({ad,placementKey:placement,citySlug:city,eventType:'impression'})},[ad,city,placement])
  if(!loaded)return null
  if(!ad)return <aside className={`gt4-ad house gt4-ad-${placement}`}><span>PARTNER</span><strong>GOOD TIMES Partner Placement</strong><a href="mailto:info@thegoodtimesworldwide.com?subject=GOOD%20TIMES%20Advertising">Advertise ↗</a></aside>
  return <aside className={`gt4-ad gt4-ad-${placement}`}><span>SPONSORED · {ad.advertiser_name}</span>{ad.image_url&&<img src={ad.image_url} alt={ad.alt_text||''}/>}<div><strong>{ad.headline}</strong>{ad.body&&<p>{ad.body}</p>}</div>{ad.cta_url&&<a href={ad.cta_url} target="_blank" rel="noreferrer" onClick={()=>trackGoodTimesAd({ad,placementKey:placement,citySlug:city,eventType:'click'})}>{ad.cta_text||'Learn more'} ↗</a>}</aside>
}

export default function GoodTimesCommandAppV3({onAuth=null}){
  const session=useMemo(()=>readSession(),[])
  const[profile,setProfile]=useState(null),[events,setEvents]=useState([]),[venues,setVenues]=useState([]),[taxonomy,setTaxonomy]=useState([]),[saved,setSaved]=useState([]),[plans,setPlans]=useState([])
  const[city,setCity]=useState('atlanta'),[tab,setTab]=useState('home'),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[intent,setIntent]=useState(''),[toast,setToast]=useState('')
  const[selectedEvent,setSelectedEvent]=useState(null),[selectedVenue,setSelectedVenue]=useState(null),[profileOpen,setProfileOpen]=useState(false)
  const[selectedCategory,setSelectedCategory]=useState(null),[selectedSubcategory,setSelectedSubcategory]=useState(null),[directoryOpen,setDirectoryOpen]=useState(false),[mapMode,setMapMode]=useState(false)
  const[conciergeText,setConciergeText]=useState(''),[conciergeBusy,setConciergeBusy]=useState(false),[conciergeResult,setConciergeResult]=useState(null),[conciergeMessage,setConciergeMessage]=useState('')
  const[follows,setFollows]=useState([]),[alertPrefs,setAlertPrefs]=useState(DEFAULT_ALERT_PREFS),[alerts,setAlerts]=useState([]),[vaultView,setVaultView]=useState('plans')

  useEffect(()=>{
    document.body.classList.add('gt-app-mode')
    const removeLegacy=()=>document.querySelectorAll('.gt-mobile-utilities,.gt-connect-fab,.gt-account-fab,.gt-party-pulse,.gt-utility-fab,[aria-label="Open GOOD TIMES utilities"],[aria-label="Close GOOD TIMES utilities"],[data-gt-legacy-utility],vercel-live-feedback').forEach(node=>node.remove())
    removeLegacy();const observer=new MutationObserver(removeLegacy);observer.observe(document.body,{childList:true,subtree:true})
    return()=>{observer.disconnect();document.body.classList.remove('gt-app-mode')}
  },[])
  const refresh=useCallback(async nextCity=>{setLoading(true);const[e,v,t]=await Promise.all([loadCanonicalEvents(nextCity,{limit:500}).catch(()=>[]),loadCanonicalVenues(nextCity,{limit:500}).catch(()=>[]),loadExploreTaxonomy().catch(()=>[])]);const hardened=hardenDisplayInventory(e||[],v||[]);setEvents(hardened.events);setVenues(hardened.venues);setTaxonomy(t||[]);setLoading(false)},[])
  const refreshAccount=useCallback(async p=>{if(!p?.id)return;const[s,i,r]=await Promise.all([loadSavedItems(p.id,session).catch(()=>[]),loadItineraries(session).catch(()=>[]),loadRadarState(session).catch(()=>({follows:[],preferences:DEFAULT_ALERT_PREFS,alerts:[]}))]);setSaved(s||[]);setPlans(i||[]);setFollows(r.follows||[]);setAlertPrefs({...DEFAULT_ALERT_PREFS,...(r.preferences||{})});setAlerts(r.alerts||[])},[session])
  useEffect(()=>{let live=true;(async()=>{const p=await loadGoodTimesProfile(session).catch(()=>null);if(!live)return;setProfile(p);const c=p?.last_city||p?.home_city||'atlanta';setCity(c);await Promise.all([refresh(c),refreshAccount(p)])})();return()=>{live=false}},[refresh,refreshAccount,session])
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(timer)},[toast])

  const savedKeys=useMemo(()=>new Set(saved.map(x=>`${x.item_type}:${x.item_id}`)),[saved])
  const followKeys=useMemo(()=>new Set(follows.filter(x=>x.is_active!==false).map(x=>`${x.entity_type}:${x.entity_id}`)),[follows])
  const today=useMemo(()=>events.filter(e=>e.event_date===todayISO()),[events])
  const week=useMemo(()=>events.filter(e=>daysAway(e.event_date)>=0&&daysAway(e.event_date)<=7),[events])
  const rankedEvents=useMemo(()=>[...events].sort((a,b)=>score(b)-score(a)||daysAway(a.event_date)-daysAway(b.event_date)),[events])
  const rankedVenues=useMemo(()=>[...venues].sort((a,b)=>score(b)-score(a)||Number(b.google_rating||0)-Number(a.google_rating||0)),[venues])
  const homeVenues=useMemo(()=>rankedVenues.filter(v=>!HOME_EXCLUDED_PLACE_TYPES.test(normalize(`${v.category_key} ${v.subcategory} ${v.venue_subcategory}`))),[rankedVenues])
  const radar=useMemo(()=>{const rows=[];const urgent=rankedEvents.find(e=>['SELLING FAST','PRESALE','NEW'].includes(statusFor(e)));const tonightPick=rankedEvents.find(e=>e.event_date===todayISO());const upcoming=rankedEvents.find(e=>daysAway(e.event_date)>0&&daysAway(e.event_date)<=7);if(urgent)rows.push({label:statusFor(urgent),item:urgent});if(tonightPick&&!rows.some(r=>r.item===tonightPick))rows.push({label:'TONIGHT',item:tonightPick});if(upcoming&&!rows.some(r=>r.item===upcoming))rows.push({label:'THIS WEEK',item:upcoming});return rows.slice(0,5)},[rankedEvents])
  const filteredEvents=useMemo(()=>{const q=normalize(query);return events.filter(item=>(!q||matchText(item).includes(q))&&matchesIntent(item,intent,true))},[events,intent,query])
  const filteredVenues=useMemo(()=>{const q=normalize(query);return rankedVenues.filter(item=>(!q||matchText(item).includes(q))&&matchesIntent(item,intent,false))},[rankedVenues,intent,query])

  useEffect(()=>{if(!session?.user?.id||!events.length||!follows.length)return;const prefMap={NEW:'just_announced',PRESALE:'presale','SELLING FAST':'selling_fast',TONIGHT:'saved_reminders'};for(const follow of follows.filter(x=>x.entity_type==='event'&&x.is_active!==false)){const item=events.find(e=>String(e.event_key)===String(follow.entity_id));if(!item)continue;const status=statusFor(item),pref=prefMap[status];if(!pref||alertPrefs?.[pref]===false)continue;const alertType=status==='NEW'?'just_announced':status==='PRESALE'?'presale':status==='SELLING FAST'?'selling_fast':'saved_reminder';void enqueueRadarAlert({alertType,objectType:'event',objectId:item.event_key,citySlug:city,title:`${status}: ${item.title}`,body:`${fmtDate(item.event_date)} · ${fmtTime(item.event_time)} · ${item.venue_name||'Location TBA'}`,actionUrl:'/',dedupeKey:`${session.user.id}:event:${item.event_key}:${status}:${item.event_date||todayISO()}`,metadata:{source:'client-radar-sync'}},session)}},[alertPrefs,city,events,follows,session])

  const changeCity=async c=>{setCity(c);setQuery('');setIntent('');setSelectedCategory(null);setSelectedSubcategory(null);setDirectoryOpen(false);await refresh(c);if(session?.user?.id)await updatePreferences(session.user.id,{last_city:c},session.access_token).catch(()=>false)}
  const toggleSave=async(type,id)=>{if(!profile?.id){setToast('Sign in to save and personalize.');return}const key=`${type}:${id}`,exists=savedKeys.has(key);try{if(exists){await unsaveItem({profileId:profile.id,itemType:type,itemId:id},session);setSaved(rows=>rows.filter(row=>`${row.item_type}:${row.item_id}`!==key));setToast('Removed from Vault.')}else{await saveItem({profileId:profile.id,itemType:type,itemId:id},session);setSaved(await loadSavedItems(profile.id,session));setToast('Saved to Vault.')}}catch(error){setToast(error.message||'Could not save.')}}
  const toggleFollow=async(type,item)=>{if(!session?.user?.id){setToast('Sign in to follow and get Radar alerts.');return}const id=type==='event'?item.event_key:item.id,key=`${type}:${id}`,exists=followKeys.has(key);try{if(exists){await unfollowEntity({entityType:type,entityId:id},session);setFollows(rows=>rows.filter(r=>`${r.entity_type}:${r.entity_id}`!==key));setToast('Radar stopped watching this.')}else{const row=await followEntity({entityType:type,entityId:id,citySlug:city,alertLevel:alertPrefs.intensity||'normal',metadata:{name:item.title||item.name,venue_name:item.venue_name||null}},session);if(row)setFollows(rows=>[row,...rows.filter(r=>`${r.entity_type}:${r.entity_id}`!==key)]);setToast('Radar is watching it.')}}catch(error){setToast(error.message||'Could not update Follow.')}}
  const updatePrefs=async patch=>{const next={...alertPrefs,...patch};setAlertPrefs(next);try{const stored=await saveRadarPreferences(next,session);setAlertPrefs({...DEFAULT_ALERT_PREFS,...stored});setToast('Radar settings saved.')}catch(error){setToast(error.message||'Could not save Radar settings.')}}
  const openEvent=e=>{setSelectedEvent(e);recordProductEvent({eventName:'event_opened',surface:tab,objectType:'event',objectId:e.event_key,city},session);recordTasteSignal({entityType:'event',entityId:e.event_key,signalType:'view',city},session)}
  const openVenue=v=>{setSelectedVenue(v);recordProductEvent({eventName:'venue_opened',surface:tab,objectType:'venue',objectId:v.id,city},session);recordTasteSignal({entityType:'venue',entityId:v.id,signalType:'view',city},session)}
  const runConcierge=async(text=conciergeText,action='recommend')=>{const clean=String(text||'').trim();if(!clean||conciergeBusy)return;setConciergeBusy(true);setConciergeMessage('');try{const result=hardenRecommendationResult(await askGoodTimesConcierge({query:clean,action,city},session));setConciergeResult(result);setConciergeMessage(result?.message||'Here are the strongest current options.');if(result?.itinerary){setPlans(rows=>[result.itinerary,...rows.filter(x=>x.id!==result.itinerary.id)]);setVaultView('plans');setToast('Plan built and saved to Vault.')}}catch(error){setConciergeMessage(error.message||'I could not verify a strong answer from current data.')}finally{setConciergeBusy(false)}}
  const shake=async mode=>{if(mode==='random'){const pool=homeVenues.filter(v=>Number(v.quality_score||0)>=70||Number(v.google_rating||0)>=4.2),source=pool.length?pool:homeVenues,pick=source[Math.floor(Math.random()*Math.max(1,source.length))];if(pick){openVenue(pick);recordTasteSignal({entityType:'venue',entityId:pick.id,signalType:'shake_random',city},session)}return}const prompts={'for-you':`Pick the strongest place for me in ${cityLabel(city)} right now based on my taste and verified inventory.`,surprise:`Surprise me with a high-quality ${cityLabel(city)} experience outside my usual habits.`,night:`Build my complete night in ${cityLabel(city)} with logical travel and an opening move, main move and optional late move.`};setConciergeText(prompts[mode]);await runConcierge(prompts[mode],mode==='night'?'itinerary':'recommend')}
  const goTab=id=>{setTab(id);if(id!=='discover'){setSelectedCategory(null);setSelectedSubcategory(null);setDirectoryOpen(false)}document.querySelector('.gt4-main')?.scrollTo?.({top:0,behavior:'instant'})}
  const goBack=()=>{
    if(tab==='discover'&&directoryOpen){setDirectoryOpen(false);setSelectedSubcategory(null);document.querySelector('.gt4-main')?.scrollTo?.({top:0,behavior:'smooth'});return}
    if(tab==='discover'&&selectedCategory){setSelectedCategory(null);setSelectedSubcategory(null);document.querySelector('.gt4-main')?.scrollTo?.({top:0,behavior:'smooth'});return}
    goTab('home')
  }
  const backLabel=tab==='discover'&&directoryOpen?'Back to subcategories':tab==='discover'&&selectedCategory?'Back to categories':'Back to Now'

  if(loading&&!events.length&&!venues.length)return <div className="gt4-loading"><AppMark/><span>Reading the city…</span></div>
  return <div className="gt4-app">
    <header className="gt4-topbar"><button className="gt4-brand" onClick={()=>goTab('home')}><AppMark/><span><strong>GOOD TIMES</strong><small>WORLDWIDE EXPERIENCE CONCIERGE</small></span></button><button className="gt4-city" onClick={()=>setProfileOpen(true)}>⌖ {cityLabel(city)}</button></header>
    <button className="gt4-radar-strip" onClick={()=>goTab('radar')}><span><i/> CITY RADAR</span><strong>{radar[0]?`${radar[0].label}: ${radar[0].item.title}`:`${follows.length} watched · ${alerts.length} alerts`}</strong><em>›</em></button>

    <main className="gt4-main">
      {tab!=='home'&&<div className="gt4-backbar"><button type="button" onClick={goBack} aria-label={backLabel}>← <span>{backLabel}</span></button></div>}
      {tab==='home'&&<>
        <section className="gt4-hero"><span>GOOD TIMES · {cityLabel(city).toUpperCase()}</span><h1>Know what’s worth it.</h1><p>Important drops, tonight’s best moves and places worth your time—without digging through the whole internet.</p><div className="gt4-ask"><input value={conciergeText} onChange={e=>setConciergeText(e.target.value)} placeholder="Ask GOOD TIMES anything…" onKeyDown={e=>{if(e.key==='Enter'){goTab('concierge');runConcierge(conciergeText)}}}/><button onClick={()=>{goTab('concierge');runConcierge(conciergeText)}}>ASK ✦</button></div><div className="gt4-quick">{['What matters tonight?','Build my night','Something different'].map(p=><button key={p} onClick={()=>{setConciergeText(p);goTab('concierge');runConcierge(p,p==='Build my night'?'itinerary':'recommend')}}>{p}</button>)}</div></section>
        <section className="gt4-shortlist"><header><div><span>YOUR SHORTLIST</span><h2>The 5</h2></div><button onClick={()=>goTab('discover')}>See everything</button></header><div>{rankedEvents.slice(0,5).map((e,i)=><button key={e.event_key} onClick={()=>openEvent(e)}><b>0{i+1}</b><span><small>{statusFor(e)}</small><strong>{e.title}</strong><em>{fmtDate(e.event_date)} · {e.venue_name||'TBA'}</em></span><i>›</i></button>)}</div></section>
        <AdSlot placement="home_radar_strip" city={city}/>
        <Section kicker="RIGHT NOW" title={today.length?'Happening today':'Next up'} action={<button onClick={()=>{goTab('discover');setIntent('Tonight')}}>See all</button>}>{(today.length?today:rankedEvents).slice(0,4).map(e=><EventCard key={e.event_key} event={e} saved={savedKeys.has(`event:${e.event_key}`)} onOpen={()=>openEvent(e)} onSave={()=>toggleSave('event',e.event_key)}/>)}</Section>
        <Section kicker="FOR YOU" title="Places worth knowing" action={<button onClick={()=>goTab('discover')}>Explore</button>}>{homeVenues.slice(0,4).map(v=><VenueCard key={v.id} venue={v} saved={savedKeys.has(`venue:${v.id}`)} onOpen={()=>openVenue(v)} onSave={()=>toggleSave('venue',v.id)}/>)}</Section>
        <AdSlot placement="home_feed_1" city={city}/>
        <Section kicker="NEXT SEVEN DAYS" title="Plan ahead">{week.slice(0,4).map(e=><EventCard key={e.event_key} event={e} saved={savedKeys.has(`event:${e.event_key}`)} onOpen={()=>openEvent(e)} onSave={()=>toggleSave('event',e.event_key)}/>)}</Section>
      </>}

      {tab==='discover'&&<section className="gt4-discover"><div className="gt4-intents">{INTENTS.map(value=><button className={intent===value?'active':''} key={value} onClick={()=>setIntent(intent===value?'':value)}>{value}</button>)}</div>{(intent||query)&&<><section className="gt4-live-results"><header><span>LIVE EXPERIENCES</span><strong>{filteredEvents.length} matches</strong></header><div>{filteredEvents.slice(0,6).map(e=><EventCard key={e.event_key} event={e} saved={savedKeys.has(`event:${e.event_key}`)} onOpen={()=>openEvent(e)} onSave={()=>toggleSave('event',e.event_key)}/>)}</div></section>{filteredVenues.length>0&&<section className="gt4-live-results"><header><span>PLACE MATCHES</span><strong>{filteredVenues.length} matches</strong></header><div>{filteredVenues.slice(0,6).map(v=><VenueCard key={v.id} venue={v} saved={savedKeys.has(`venue:${v.id}`)} onOpen={()=>openVenue(v)} onSave={()=>toggleSave('venue',v.id)}/>)}</div></section>}</>}<AdSlot placement="discover_inline" city={city}/><ExploreTaxonomyBrowser taxonomy={taxonomy} directory={venues} cityName={cityLabel(city)} query={query} onQuery={setQuery} selectedCategory={selectedCategory} selectedSubcategory={selectedSubcategory} onCategory={setSelectedCategory} onSubcategory={setSelectedSubcategory} directoryOpen={directoryOpen} onDirectoryOpen={setDirectoryOpen} mapMode={mapMode} onMapMode={setMapMode} renderVenue={venue=><VenueCard key={venue.id} venue={venue} saved={savedKeys.has(`venue:${venue.id}`)} onOpen={()=>openVenue(venue)} onSave={()=>toggleSave('venue',venue.id)}/>} /></section>}

      {tab==='concierge'&&<section className="gt4-screen"><div className="gt4-head"><span>GOOD TIMES CONCIERGE</span><h1>Tell us the night.<br/>We make the decisions.</h1><p>Ask naturally. Use the guided builder only when you want extra control.</p></div><div className="gt4-concierge"><textarea value={conciergeText} onChange={e=>setConciergeText(e.target.value)} placeholder="Date night tonight, upscale dinner, then R&B, under $250 for two…"/><div><button onClick={()=>runConcierge(conciergeText,'recommend')} disabled={conciergeBusy}>Recommend</button><button className="primary" onClick={()=>runConcierge(conciergeText,'itinerary')} disabled={conciergeBusy}>Build my night ✦</button></div>{conciergeBusy&&<p>Checking timing, fit and current inventory…</p>}{conciergeMessage&&<blockquote>{conciergeMessage}</blockquote>}</div><section className="gt4-shake"><header><span>GOOD TIMES SHAKE</span><h2>Don’t want to decide?</h2></header><div>{SHAKE_MODES.map(([id,title,body])=><button key={id} onClick={()=>shake(id)}><i>✦</i><strong>{title}</strong><small>{body}</small></button>)}</div></section><AdSlot placement="concierge_inline" city={city}/>{conciergeResult?.events?.length>0&&<Section kicker="CONCIERGE PICKS" title="Events that fit">{conciergeResult.events.slice(0,5).map(e=><EventCard key={e.event_key} event={e} saved={savedKeys.has(`event:${e.event_key}`)} onOpen={()=>openEvent(e)} onSave={()=>toggleSave('event',e.event_key)}/>)}</Section>}{conciergeResult?.venues?.length>0&&<Section kicker="CONCIERGE PICKS" title="Places that fit">{conciergeResult.venues.slice(0,5).map(v=><VenueCard key={v.id} venue={v} saved={savedKeys.has(`venue:${v.id}`)} onOpen={()=>openVenue(v)} onSave={()=>toggleSave('venue',v.id)}/>)}</Section>}<details className="gt4-builder"><summary>Fine-tune with the guided builder</summary><BuildMyNightPanel cityName={cityLabel(city)} busy={conciergeBusy} onBuild={prompt=>{setConciergeText(prompt);runConcierge(prompt,'itinerary')}}/></details></section>}

      {tab==='radar'&&<section className="gt4-screen"><div className="gt4-head"><span>GOOD TIMES RADAR</span><h1>Never hear about it late.</h1><p>Follow the things that matter. Radar watches announcements, presales, urgency and changes.</p></div><section className="gt4-radar-settings"><label>ALERT INTENSITY<select value={alertPrefs.intensity||'normal'} onChange={e=>updatePrefs({intensity:e.target.value})}><option value="quiet">Quiet</option><option value="normal">Normal</option><option value="never_miss">Never Miss</option></select></label><div>{[['just_announced','Just announced'],['presale','Presales'],['selling_fast','Selling fast'],['weekend_brief','Weekend brief']].map(([key,label])=><label key={key}><span>{label}</span><input type="checkbox" checked={alertPrefs[key]!==false} onChange={e=>updatePrefs({[key]:e.target.checked})}/></label>)}</div></section><Section kicker="CITY SIGNALS" title="What needs attention">{radar.length?radar.map(r=><EventCard key={`${r.label}-${r.item.event_key}`} event={r.item} saved={savedKeys.has(`event:${r.item.event_key}`)} onOpen={()=>openEvent(r.item)} onSave={()=>toggleSave('event',r.item.event_key)}/>):<Empty title="Radar is quiet" body="Follow events and places you care about. GOOD TIMES will watch them here."/>}</Section>{alerts.length>0&&<section className="gt4-alerts"><span>YOUR ALERTS</span>{alerts.slice(0,12).map(a=><article key={a.id}><small>{String(a.alert_type||'alert').replaceAll('_',' ')}</small><strong>{a.title}</strong><p>{a.body}</p></article>)}</section>}<section className="gt4-watchlist"><header><span>WATCHLIST</span><strong>{follows.length} followed</strong></header>{follows.length?follows.map(f=><div key={`${f.entity_type}:${f.entity_id}`}><span><strong>{f.metadata?.name||`${f.entity_type}: ${f.entity_id}`}</strong><small>{f.city_slug||cityLabel(city)}</small></span><em>{f.alert_level||'normal'}</em></div>):<p>Use “Follow + alerts” on any event or place to add it here.</p>}</section></section>}

      {tab==='vault'&&<section className="gt4-screen"><div className="gt4-head"><span>YOUR VAULT</span><h1>Everything you kept.</h1><p>Plans and saved things belong together—one destination, different views.</p></div><div className="gt4-vault-tabs"><button className={vaultView==='plans'?'active':''} onClick={()=>setVaultView('plans')}>Plans <b>{plans.length}</b></button><button className={vaultView==='saved'?'active':''} onClick={()=>setVaultView('saved')}>Saved <b>{saved.length}</b></button></div><AdSlot placement="saved_partner" city={city}/>{vaultView==='plans'&&(plans.length?<div className="gt4-plans">{plans.map(p=><article key={p.id}><header><span>{String(p.status||'draft').toUpperCase()}</span><h2>{p.name||'GOOD TIMES plan'}</h2><p>{fmtDate(p.itinerary_date)} · {cityLabel(p.city_id||city)} · {p.group_size||1} guests</p></header><div>{(p.stops||[]).map((s,i)=><section key={`${s.id||s.name}-${i}`}><b>{String(i+1).padStart(2,'0')}</b><span><small>{s.role||s.type||'STOP'}</small><strong>{s.name}</strong><em>{s.time?fmtTime(s.time):'Time flexible'} · {s.venue||s.address||''}</em></span></section>)}</div></article>)}</div>:<Empty title="No plans yet" body="Tell Concierge what you want and GOOD TIMES will save the route here." action={<button className="gt4-primary" onClick={()=>goTab('concierge')}>Build a plan</button>}/>)}{vaultView==='saved'&&(saved.length?<><Section kicker="SAVED EVENTS" title={`${events.filter(e=>savedKeys.has(`event:${e.event_key}`)).length} experiences`}>{events.filter(e=>savedKeys.has(`event:${e.event_key}`)).map(e=><EventCard key={e.event_key} event={e} saved onOpen={()=>openEvent(e)} onSave={()=>toggleSave('event',e.event_key)}/>)}</Section><Section kicker="SAVED PLACES" title={`${venues.filter(v=>savedKeys.has(`venue:${v.id}`)).length} places`}>{venues.filter(v=>savedKeys.has(`venue:${v.id}`)).map(v=><VenueCard key={v.id} venue={v} saved onOpen={()=>openVenue(v)} onSave={()=>toggleSave('venue',v.id)}/>)}</Section></>:<Empty title="Nothing saved yet" body="Save events and places you want to remember. They will stay here." action={<button className="gt4-primary" onClick={()=>goTab('discover')}>Explore Atlanta</button>}/>)}</section>}
    </main>

    <nav className="gt4-nav">{NAV.map(([id,icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>goTab(id)}><span>{icon}</span><small>{label}</small></button>)}</nav>

    {selectedEvent&&<div className="gt4-modal-bg" onMouseDown={()=>setSelectedEvent(null)}><article className="gt4-detail" onMouseDown={e=>e.stopPropagation()}><button className="gt4-detail-back" onClick={()=>setSelectedEvent(null)}>← Back</button>{safeMedia(selectedEvent.image_url)?<img src={safeMedia(selectedEvent.image_url)} alt=""/>:<div className="gt4-detail-fallback"><AppMark/></div>}<div><span>{statusFor(selectedEvent)} · {cat(selectedEvent.category_key)}</span><h2>{selectedEvent.title}</h2><p>{fmtDate(selectedEvent.event_date)} · {fmtTime(selectedEvent.event_time)} · {selectedEvent.venue_name||'TBA'}</p><section><strong>GOOD TIMES TAKE</strong><p>{selectedEvent.reasons?.[0]||'This made the current shortlist based on timing, quality and current recommendation signals.'}</p></section><div className="gt4-detail-actions"><button onClick={()=>toggleSave('event',selectedEvent.event_key)}>{savedKeys.has(`event:${selectedEvent.event_key}`)?'Saved ✓':'Save'}</button><button onClick={()=>toggleFollow('event',selectedEvent)}>{followKeys.has(`event:${selectedEvent.event_key}`)?'Following ✓':'Follow + alerts'}</button>{selectedEvent.ticket_url&&<a href={selectedEvent.ticket_url} target="_blank" rel="noreferrer">Tickets</a>}<button className="primary" onClick={()=>{const p=`Build my night around ${selectedEvent.title} at ${selectedEvent.venue_name||'this venue'} on ${fmtDate(selectedEvent.event_date)}.`;setSelectedEvent(null);goTab('concierge');setConciergeText(p);runConcierge(p,'itinerary')}}>Plan around this ✦</button></div></div></article></div>}
    {selectedVenue&&<div className="gt4-modal-bg" onMouseDown={()=>setSelectedVenue(null)}><article className="gt4-detail" onMouseDown={e=>e.stopPropagation()}><button className="gt4-detail-back" onClick={()=>setSelectedVenue(null)}>← Back</button>{safeMedia(selectedVenue.hero_image)?<img src={safeMedia(selectedVenue.hero_image)} alt=""/>:<div className="gt4-detail-fallback"><AppMark/></div>}<div><span>{cat(selectedVenue.category_key)} · {selectedVenue.neighborhood||cityLabel(city)}</span><h2>{selectedVenue.name}</h2><p>{selectedVenue.short_desc||selectedVenue.insider_tip||'Verified GOOD TIMES place.'}</p><section><strong>KNOW BEFORE YOU GO</strong><p>{[selectedVenue.price_range,selectedVenue.dress_code,selectedVenue.reservation_req,selectedVenue.hours_summary].filter(Boolean).join(' · ')||'Confirm current hours and entry details before heading out.'}</p></section><div className="gt4-detail-actions"><button onClick={()=>toggleSave('venue',selectedVenue.id)}>{savedKeys.has(`venue:${selectedVenue.id}`)?'Saved ✓':'Save'}</button><button onClick={()=>toggleFollow('venue',selectedVenue)}>{followKeys.has(`venue:${selectedVenue.id}`)?'Following ✓':'Follow + alerts'}</button>{selectedVenue.booking_link&&<a href={selectedVenue.booking_link} target="_blank" rel="noreferrer">Book</a>}<button className="primary" onClick={()=>{const p=`Plan a complete night that includes ${selectedVenue.name} in ${selectedVenue.neighborhood||cityLabel(city)}.`;setSelectedVenue(null);goTab('concierge');setConciergeText(p);runConcierge(p,'itinerary')}}>Plan a night here ✦</button></div></div></article></div>}
    {profileOpen&&<div className="gt4-modal-bg" onMouseDown={()=>setProfileOpen(false)}><aside className="gt4-profile" onMouseDown={e=>e.stopPropagation()}><button className="gt4-detail-back" onClick={()=>setProfileOpen(false)}>← Back</button><AppMark/><span>YOUR GOOD TIMES</span><h2>{profile?.full_name||session?.user?.email||'Guest'}</h2><p>{session?.user?.email||'Browse freely. Sign in when you want to save, follow and personalize.'}</p><label>HOME CITY<select value={city} onChange={e=>changeCity(e.target.value)}>{cityOptions.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><div className="gt4-profile-stats"><div><strong>{saved.length}</strong><span>Saved</span></div><div><strong>{plans.length}</strong><span>Plans</span></div><div><strong>{follows.length}</strong><span>Following</span></div></div>{!session&&onAuth&&<button className="gt4-primary gt4-profile-auth" onClick={onAuth}>Sign in or create account</button>}{session&&<button className="danger" onClick={()=>{clearSession();window.location.reload()}}>Sign out</button>}</aside></div>}
    {toast&&<div className="gt4-toast">{toast}</div>}
  </div>
}
