/** Web clone only. All customer accounts, writes, purchases and provider calls are mocked. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {chromium} from 'playwright-core';
import {install,makeState} from './complete-upgrade-fixtures.mjs';
import {readWebRoute} from '../src/features/experience/web-navigation.js';
const OUT='qa/evidence', BASE='http://127.0.0.1:4190';
fs.mkdirSync(OUT,{recursive:true});
const report={scope:'GOOD TIMES isolated web clone',sourceCommit:process.env.WEB_TEST_COMMIT||null,mobileRepositoryWritten:false,productionDatabaseWritten:false,liveAuthenticationVerified:false,livePaymentsVerified:false,liveDeploymentVerified:false,mode:'Loopback browser with controlled account/content fixtures; actual compiled UI and local brand assets.',checks:[],screenshots:[],errors:[],viewports:[]};
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const log=async(name,fn)=>{try{const detail=await fn();report.checks.push({name,status:'PASS',detail:detail??null});console.log('PASS '+name);return true}catch(e){report.checks.push({name,status:'FAIL',error:e.message});report.errors.push({name,error:e.message});console.log('FAIL '+name+': '+e.message);return false}};
async function snap(page,name){const file=name+'.jpg';await page.screenshot({path:path.join(OUT,file),type:'jpeg',quality:64,animations:'disabled'});report.screenshots.push(file)}
async function nav(page,label){await page.locator('.gt5-nav').getByRole('button',{name:label,exact:true}).click();await pause(160)}
async function layout(page,screen,width){
 const result=await page.evaluate(()=>{const box=s=>document.querySelector(s)?.getBoundingClientRect().toJSON();const main=document.querySelector('.gt5-main');return {width:innerWidth,height:innerHeight,root:box('#root'),app:box('.gt5-app'),nav:box('.gt5-nav'),main:box('.gt5-main'),overflow:document.documentElement.scrollWidth-innerWidth,mainOverflow:main.scrollWidth-main.clientWidth,visibleImages:[...document.images].filter(i=>i.getBoundingClientRect().height>0).map(i=>({src:i.getAttribute('src'),loaded:i.complete&&i.naturalWidth>0})),buttons:[...document.querySelectorAll('.gt5-nav button')].map(b=>({name:b.innerText,rect:b.getBoundingClientRect().toJSON()}))}});
 assert.ok(result.app&&result.main&&result.nav,'Customer shell must be rendered');assert.ok(result.overflow<=1,'Document horizontal overflow: '+result.overflow);assert.ok(result.mainOverflow<=1,'Content horizontal overflow: '+result.mainOverflow);
 if(width>=1024){assert.ok(Math.abs(result.app.width-width)<=2,'Desktop app must fill browser width');assert.ok(result.nav.width<300,'Desktop sidebar is not a bottom bar');assert.ok(result.main.left>=result.nav.right-2,'Sidebar overlaps content');assert.ok(result.main.right<=width+1,'Content escapes browser');assert.ok(result.nav.height>result.nav.width,'Desktop sidebar must be vertical')}
 assert.ok(result.buttons.every(b=>b.rect.width>30&&b.rect.height>30),'All navigation controls need usable hit areas');
 report.viewports.push({screen,...result});return {width,mainWidth:result.main.width,railWidth:result.nav.width};
}
function visibleText(page){return page.locator('body').innerText()}
async function dismiss(page){await page.keyboard.press('Escape').catch(()=>{});const back=page.getByRole('button',{name:'Close itinerary'});if(await back.count())await back.click().catch(()=>{});page.once('dialog',d=>d.accept());}
const server=spawn(process.execPath,['scripts/serve-dist.mjs'],{env:{...process.env,PORT:'4190',API_ORIGIN:'http://127.0.0.1:9',GT_UI_HEALTH_FIXTURE:'healthy'},stdio:'inherit'});
let browser;
try{
 for(let i=0;i<80;i++){try{if((await fetch(BASE+'/api/health')).ok)break}catch{}await pause(100)}
 browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 await log('Browser URL parsing is bounded to existing primary sections',async()=>{for(const tab of ['home','places','plan','entertainment','profile'])assert.equal(readWebRoute(BASE+'/?view='+tab).tab,tab);assert.equal(readWebRoute(BASE+'/?view=javascript:alert(1)').tab,'home')});
 for(const width of [1024,1280,1366,1440,1920,768,390]){
  const context=await browser.newContext({viewport:{width,height:width>=1024?900:width===768?1024:844},timezoneId:'America/New_York',reducedMotion:'reduce'}),state=makeState(),page=await context.newPage(),browserErrors=[];
  await install(context,state);page.setDefaultTimeout(7000);page.on('pageerror',e=>browserErrors.push(e.message));page.on('dialog',d=>d.accept());
  // Only actual public, read-only image/font resources may leave loopback. Account/API traffic remains fixture-intercepted.
  await context.route('**/storage/v1/object/public/**',route=>{if(route.request().method()==='GET'&&route.request().resourceType()==='image')return route.continue();return route.fallback()});
  await context.route('https://fonts.googleapis.com/**',route=>route.continue());
  await context.route('https://fonts.gstatic.com/**',route=>route.continue());
  try{
   const loaded=await log(`${width}: full Home and real primary navigation`,async()=>{await page.goto(BASE,{waitUntil:'domcontentloaded'});await page.locator('.gtc-home .gtc-card').first().waitFor();assert.deepEqual(await page.locator('.gt5-nav button small').allTextContents(),['Home','Places','Plan','Entertainment','Profile']);await layout(page,'home',width);await snap(page,`${width}-home`)});
   if(!loaded){await snap(page,`${width}-startup-failure`).catch(()=>{});continue}
   await log(`${width}: local logo and bundled venue images resolve`,async()=>{for(const asset of ['/good-times-logo-official.png','/icons/good-times-192.png','/venues/opium.jpg','/venues/revel.webp','/reference-base/atlanta-rooftop.webp']){const r=await page.request.get(BASE+asset);assert.equal(r.status(),200,asset);assert.ok(r.headers()['content-type']?.startsWith('image/'),asset+' must not return SPA HTML')}});
   await log(`${width}: Home Tonight / Upcoming / For You controls`,async()=>{for(const label of ['Tonight','Upcoming','For You']){await page.locator('.gt5-home-modes').getByRole('button',{name:label,exact:true}).click();await pause(180);assert.equal(await page.locator('.gt5-home-modes').getByRole('button',{name:label,exact:true}).getAttribute('aria-pressed'),'true')}await layout(page,'home-tabs',width)});
   await log(`${width}: Places and restaurant entrance`,async()=>{await nav(page,'Places');await page.locator('.gtc-place-lanes').waitFor();assert.equal(await page.locator('.gtc-place-lanes>button').count(),6);await layout(page,'places',width);await snap(page,`${width}-places`);await page.locator('.gtc-place-lanes>button').filter({hasText:'Restaurants'}).click();await pause(300);assert.ok(/restaurant/i.test(await visibleText(page)));await snap(page,`${width}-restaurants`)});
   await log(`${width}: Entertainment categories and timing controls`,async()=>{await nav(page,'Entertainment');await page.locator('.gtc-entertainment-lanes').waitFor();assert.equal(await page.locator('.gtc-entertainment-lanes>button').count(),9);for(const label of ['This Weekend','Upcoming','Tonight']){await page.locator('.gtc-entertainment-time').getByRole('button',{name:label,exact:true}).click();assert.equal(await page.locator('.gtc-entertainment-time').getByRole('button',{name:label,exact:true}).getAttribute('aria-pressed'),'true')}await layout(page,'entertainment',width);await snap(page,`${width}-entertainment`)});
   await log(`${width}: every Entertainment category button routes`,async()=>{for(const title of ['Nightlife','Concerts','Festivals + Events','Sports','Comedy + Live','Interactive','Family','Attractions']){await nav(page,'Entertainment');await page.locator('.gtc-entertainment-lane').filter({has:page.locator('strong',{hasText:new RegExp('^'+title.replace(/[+]/g,'\\+')+'$')})}).click();await pause(250);assert.equal(await page.locator('.gtc-entertainment-lanes').count(),0,title+' did not leave category launcher');assert.ok(await page.locator('.gt5-main').innerText(),title+' has no content');await layout(page,'lane-'+title,width)}});
   await log(`${width}: Bars & Lounges, categories, save, detail and return`,async()=>{await nav(page,'Entertainment');await page.locator('.gtc-entertainment-lane').filter({hasText:'Bars & Lounges'}).click();await page.locator('[data-gt-subcategory="nightclubs"]').click();await page.locator('.gt-compact-results .gtc-card').first().waitFor();await layout(page,'venue-directory',width);const save=page.locator('.gt-compact-results .gtc-save').first();await save.click();await page.waitForFunction(()=>document.querySelector('.gt-compact-results .gtc-save')?.getAttribute('aria-pressed')==='true');assert.equal(await page.locator('.gtc-detail').count(),0,'Saving must not open detail');await page.locator('.gt-compact-results .gtc-card-open').first().click();await page.locator('.gtc-detail').waitFor();await snap(page,`${width}-venue-detail`);await page.getByRole('tab',{name:'Information',exact:true}).click();assert.ok((await visibleText(page)).includes('Source & details'));await page.keyboard.press('Escape');await page.locator('.gtc-detail').waitFor({state:'detached'});await page.locator('.gt-compact-results .gtc-card').first().waitFor();assert.ok(state.saved.length>0)});
   await log(`${width}: Map view is selectable without losing directory`,async()=>{const toggle=page.locator('.gt2-explore-toggle');await toggle.getByRole('button',{name:'Map',exact:true}).click();await page.locator('.gt-compact-map').waitFor();await snap(page,`${width}-map`);await layout(page,'map',width)});
   await log(`${width}: Profile library, following, preferences, account`,async()=>{await nav(page,'Profile');await page.locator('.gtc-profile-hub').waitFor();for(const label of ['Following','Preferences','Account','Library']){await page.locator('.gtc-profile-tabs').getByRole('button',{name:label,exact:true}).click();assert.equal(await page.locator('.gtc-profile-tabs').getByRole('button',{name:label,exact:true}).getAttribute('aria-pressed'),'true')}await page.getByRole('tab',{name:/^Places ·/}).click();await page.locator('.gtc-saved .gtc-card').first().waitFor();await layout(page,'saved-places',width);await snap(page,`${width}-profile-library`)});
   await log(`${width}: guided planner generates but does not auto-save/book`,async()=>{await nav(page,'Plan');await page.locator('.gtc-mood-grid').waitFor();await layout(page,'planner',width);await snap(page,`${width}-planner`);const count=state.plans.length;await page.getByRole('button',{name:/^Continue/}).click();await page.getByRole('button',{name:/^Continue/}).click();await page.getByRole('checkbox',{name:/Everyone.*21/}).check();await page.getByRole('button',{name:/^Continue/}).click();await page.getByRole('button',{name:'Build my plan',exact:true}).click();await page.locator('.gtc-itinerary').waitFor();assert.ok(await page.locator('.gtc-stop').count()>0);assert.equal(state.plans.length,count);await snap(page,`${width}-itinerary`)});
   await log(`${width}: itinerary save and persisted Profile library`,async()=>{await page.getByRole('button',{name:'Save plan',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.gtc-detail-toolbar')?.textContent.includes('Saved plan'));assert.equal(state.plans.length,1);await page.getByRole('button',{name:'Close itinerary'}).click();await nav(page,'Profile');await page.locator('.gtc-profile-tabs').getByRole('button',{name:'Library',exact:true}).click();await page.getByRole('tab',{name:/^Plans ·/}).click();await page.locator('.gtc-plan-tile').first().waitFor();await page.reload({waitUntil:'domcontentloaded'});await page.locator('.gtc-plan-tile').first().waitFor();assert.ok(page.url().includes('view=profile'))});
   await log(`${width}: Ask and Shake interfaces`,async()=>{await nav(page,'Plan');await page.getByRole('button',{name:'Ask',exact:true}).click();await page.getByRole('textbox',{name:'Ask GOOD TIMES'}).fill('A relaxed night in Midtown');await page.getByRole('button',{name:'Find my options',exact:true}).click();await page.locator('.gtc-planner .gtc-card').first().waitFor();await snap(page,`${width}-ask`);await page.getByRole('button',{name:'Shake',exact:true}).click();assert.ok(/shake/i.test(await page.locator('.gtc-planner').innerText()));await snap(page,`${width}-shake`)});
   await log(`${width}: browser Back, Forward and reload preserve primary page`,async()=>{await nav(page,'Home');await nav(page,'Places');await nav(page,'Entertainment');await page.goBack();await page.locator('.gtc-place-lanes').waitFor();await page.goForward();await page.locator('.gtc-entertainment-lanes').waitFor();await page.reload({waitUntil:'domcontentloaded'});await page.locator('.gtc-entertainment-lanes').waitFor();assert.equal(await page.locator('.gt5-nav button[aria-current="page"] small').innerText(),'Entertainment')});
   await log(`${width}: Radar opens and returns via primary navigation`,async()=>{await page.getByRole('button',{name:'Open GOOD TIMES Radar'}).click();await page.locator('.gt5-app[data-screen="radar"]').waitFor();await layout(page,'radar',width);await snap(page,`${width}-radar`);await nav(page,'Home');await page.locator('.gtc-home').waitFor()});
   await log(`${width}: search submission produces global results`,async()=>{await nav(page,'Home');await page.getByRole('textbox',{name:'Search Atlanta',exact:true}).fill('Opium');await page.getByRole('textbox',{name:'Search Atlanta',exact:true}).press('Enter');await page.locator('.gt5-app[data-screen="search"]').waitFor();assert.ok(/opium/i.test(await visibleText(page)));await snap(page,`${width}-search`)});
   await log(`${width}: no browser JavaScript crashes`,async()=>assert.deepEqual(browserErrors,[]));
   if(width===1440){
    await log('Failures: a rejected save is not displayed as success',async()=>{await nav(page,'Entertainment');await page.locator('.gtc-entertainment-lane').filter({hasText:'Bars & Lounges'}).click();await page.locator('[data-gt-subcategory="nightclubs"]').click();await page.locator('.gt-compact-results .gtc-card').first().waitFor();state.failSave=true;const count=state.saved.length;await page.locator('.gt-compact-results .gtc-save').nth(1).click();await pause(350);assert.equal(state.saved.length,count);assert.equal(await page.locator('.gt-compact-results .gtc-save').nth(1).getAttribute('aria-pressed'),'false');state.failSave=false});
    await log('Failures: directory error has actionable retry',async()=>{state.failDirectory=true;await page.getByRole('button',{name:'Refresh places'}).click();await page.getByRole('button',{name:'Retry places'}).waitFor();state.failDirectory=false;await page.getByRole('button',{name:'Retry places'}).click();await page.locator('.gt-compact-results .gtc-card').first().waitFor()});
    await log('Failures: failed plan edit preserves saved plan and retry works',async()=>{await nav(page,'Profile');await page.locator('.gtc-plan-tile').first().click();await page.locator('.gtc-itinerary').waitFor();const before=state.plans[0].name;await page.getByRole('textbox',{name:'Plan name'}).fill('Edited desktop QA night');state.failPlanSave=true;await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('alert').filter({hasText:'Could not update plan'}).waitFor();assert.equal(state.plans[0].name,before);state.failPlanSave=false;await page.getByRole('button',{name:'Save changes'}).click();await pause(350);assert.equal(state.plans[0].name,'Edited desktop QA night');await page.getByRole('button',{name:'Close itinerary'}).click()});
   }
  }finally{fs.writeFileSync(path.join(OUT,width+'-final-dom.txt'),await visibleText(page).catch(()=>''));await context.close()}
 }
}finally{
 await browser?.close();server.kill();report.completedAt=new Date().toISOString();report.passed=report.errors.length===0;report.passCount=report.checks.filter(x=>x.status==='PASS').length;report.failCount=report.errors.length;fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify(report,null,2));
 const lines=['# GOOD TIMES web verification','',`Passed: ${report.passCount}. Failed: ${report.failCount}.`,'','Scope: compiled UI, controlled account/content fixtures, actual copied local image assets.','Live OAuth, production payments, production deployment and live account synchronization are NOT certified by this report.','No source app repository or production database writes.','',...report.checks.map(x=>`- ${x.status}: ${x.name}${x.error?' — '+x.error.split('\n')[0]:''}`)];fs.writeFileSync(path.join(OUT,'REPORT.md'),lines.join('\n')+'\n');console.log(JSON.stringify({pass:report.passCount,fail:report.failCount,errors:report.errors},null,2));
}
if(report.errors.length)process.exitCode=1;
