import React,{useEffect,useRef,useState} from 'react'
import {Picture,State,ActionLink,Section} from './Cards.jsx'
import {EventCollection,CollectionGrid} from './Collections.jsx'
import {list,safeLink,safeImage,displayDate,displayTime,labelFor,identity,cleanTitle} from './model.js'
import {restaurantFactRows} from './restaurant-facts.js'
import {restaurantActionLabel} from './restaurant-actions.js'
import {useBrowse} from './useBrowse.js'
import {shareContent} from '../../../native.js'
export function useDialogFocus(ref,onClose){const close=useRef(onClose);close.current=onClose;useEffect(()=>{const prev=document.activeElement,root=ref.current;if(!root)return;const blocked=[...document.querySelectorAll('.gt5-main,.gt5-nav,.gt5-topbar')];for(const x of blocked)x.inert=true;const focusables=()=>[...root.querySelectorAll('button:not(:disabled),a[href],input,select,textarea,[tabindex="0"]')].filter(x=>x.getClientRects().length);focusables()[0]?.focus();const listener=e=>{if(e.key==='Escape')close.current?.();if(e.key==='Tab'){const items=focusables(),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};root.addEventListener('keydown',listener);return()=>{for(const x of blocked)x.inert=false;root.removeEventListener('keydown',listener);prev?.focus?.()}},[])}
export default function Details({item,kind,onClose,onSave,saved,onPlan,onFollow,following,onEvent,savedKeys,saveItem,now}){
 const ref=useRef(null);useDialogFocus(ref,onClose)
 const event=kind==='event',[tab,setTab]=useState('overview'),[photo,setPhoto]=useState(0),[notice,setNotice]=useState('')
 const live=useBrowse({kind:'venue',id:item.id},!event&&/^[a-f0-9-]{36}$/i.test(item.id)),venue=live.items[0],record=venue?{...item,...venue}:item
 const restaurantFacts=event?[]:restaurantFactRows(record.restaurant_profile)
 const images=[...new Set([event?record.image_url:record.hero_image,...list(record.photos)].filter(x=>typeof x==='string'&&safeImage(x)))],title=cleanTitle(record.title||record.name),address=record.address||record.venue_address
 const phone=String(record.phone||'').replace(/[^+\d]/g,''),external=safeLink(record.ticket_url||record.booking_link||record.website),source=safeLink(record.source_url||record.website)
 const share=async()=>{const url=new URL(window.location.origin);url.searchParams.set('item',identity(item));url.searchParams.set('kind',kind);const ok=await shareContent({title,text:[title,event?`${displayDate(record.event_date)} · ${displayTime(record.event_time)}`:record.neighborhood,'Found on GOOD TIMES'].filter(Boolean).join('\n'),url:url.toString()});setNotice(ok?'Link shared.':'Share cancelled or unavailable.')}
 return <div className="gt5-overlay gtc-overlay" role="dialog" aria-modal="true" aria-label={title} ref={ref}><article className="gt5-detail gtc-detail"><header className="gtc-detail-toolbar"><button className="gt5-detail-back" onClick={onClose} aria-label="Back to results">← Back</button><button onClick={share}>Share ↗</button><button onClick={onSave} aria-pressed={saved}>{saved?'Saved ✓':'Save ♡'}</button></header>
 <div className="gtc-detail-cover"><Picture src={images[photo]} kind={event?'Event':'Place'}/>{images.length>1&&<div className="gtc-gallery-controls"><button onClick={()=>setPhoto(x=>(x-1+images.length)%images.length)} aria-label="Previous photo">‹</button><span>{photo+1} / {images.length}</span><button onClick={()=>setPhoto(x=>(x+1)%images.length)} aria-label="Next photo">›</button></div>}</div>
 <div className="gtc-detail-copy"><small className="gtc-category">{event?labelFor(record.category_key):record.venue_subcategory||record.subcategory||labelFor(record.category_key)}</small><h1>{title}</h1><p className="gtc-detail-sub">{event?`${displayDate(record.event_date)} · ${displayTime(record.event_time)}`:record.neighborhood||'Atlanta'}{record.price_range?` · ${record.price_range}`:''}</p>{event&&<p>{record.venue_name||'Location to confirm'}</p>}
 <div className="gtc-detail-primary">{external&&<ActionLink href={external} className="primary">{event?'View tickets':restaurantActionLabel(record)}</ActionLink>}<button onClick={()=>onPlan(record)}>Plan around this ＋</button></div>
 {notice&&<p role="status">{notice}</p>}
 {!event&&live.status==='error'&&<p className="gtc-note" role="alert">Latest venue details could not refresh. <button onClick={live.reload}>Retry</button></p>}
 {!event&&record.restaurant_profile_state==='unavailable'&&<p className="gtc-note" role="status">Additional restaurant details could not refresh. <button onClick={live.reload}>Retry details</button></p>}
 <div className="gtc-tabs" role="tablist" aria-label="Details">{['overview',...(!event?['events']:[]),'information'].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='overview'?'Overview':t==='events'?'Upcoming here':'Information'}</button>)}</div>
 {tab==='overview'&&<section className="gtc-overview">{(record.description||record.long_desc||record.short_desc)&&<p>{record.description||record.long_desc||record.short_desc}</p>}<div className="gtc-detail-facts" aria-label="Listing facts">{[[event?'Time':'Hours',event?(record.time_label||displayTime(record.event_time)):(record.hours_summary||'Confirm with venue')],['Location',address||record.venue_name||record.neighborhood],['Age / entry',record.age_requirement||record.age_range],['Dress code',record.dress_code],...restaurantFacts].filter(([,v])=>v).map(([k,v])=><div key={k}><small>{k}</small><span>{v}</span></div>)}</div>{restaurantFacts.length>0&&record.restaurant_profile?.partial&&<p className="gtc-note">Available recorded restaurant details. Additional attributes remain under review.</p>}{restaurantFacts.some(([key])=>key==='Dietary options')&&<p className="gtc-note">Confirm dietary requirements and allergen information directly with the venue.</p>}{record.is_black_owned===true&&!restaurantFacts.some(([key])=>key==='Ownership')&&<p className="gtc-note">Black-owned · recorded in GOOD TIMES</p>}<div className="gtc-detail-support">{phone&&<a href={`tel:${phone}`}>Call</a>}{address&&<ActionLink href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(address)}>Directions</ActionLink>}{onFollow&&<button onClick={onFollow}>{following?'Following ✓':'Follow + alerts'}</button>}</div><p className="gtc-note">Listings are recommendations. Check current hours, availability and entry rules before going.</p></section>}
 {tab==='events'&&<EventCollection venueId={record.id} inline {...{now,savedKeys,onEvent}} onSave={saveItem}/>}
 {tab==='information'&&<section><h2>Source & details</h2>{source?<ActionLink href={source}>View source</ActionLink>:<p>No direct source link is available for this entry.</p>}{record.updated_at&&<p>Record updated {displayDate(record.updated_at.slice(0,10))}</p>}{record.verified_at&&<p>Verified {displayDate(record.verified_at.slice(0,10))}</p>}{record.photo_credit&&<p>Photo: {record.photo_credit}</p>}<p className="gtc-note">Record freshness is not a ticket, table or entry confirmation.</p><a className="gtc-support-link" href={'/support.html?listing='+encodeURIComponent(identity(item))}>Report a listing issue ↗</a></section>}
 </div></article></div>
}
export function Saved({items=[],plans=[],events=[],venues=[],onEvent,onVenue,onSave,onPlan,onExplore,onEntertainment,onBuild,session}){
 const [view,setView]=useState('plans'),[resolved,setResolved]=useState([]),[error,setError]=useState(''),[retry,setRetry]=useState(0)
 useEffect(()=>{if(view==='plans')return;const known=new Map([...events,...venues].map(i=>[i.event_key||i.id,i])),missing=items.filter(i=>!known.has(i.item_id));setResolved([...known.values()]);setError('');if(!missing.length)return;const c=new AbortController();const batches=[];for(let n=0;n<missing.length;n+=24)batches.push(missing.slice(n,n+24));(async()=>{for(const batch of batches){const ids=batch.map(i=>({kind:i.item_type,id:i.item_id}));const response=await fetch('/api/saved-content?items='+encodeURIComponent(JSON.stringify(ids)),{signal:c.signal,cache:'no-store'});const body=await response.json();if(!response.ok||!body.ok)throw new Error('Some saved details could not refresh.');setResolved(old=>{const all=new Map(old.map(i=>[identity(i),i]));for(const i of body.items)all.set(identity(i),i);return [...all.values()]})}})().catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[view,items.map(i=>i.item_type+':'+i.item_id).join('|'),retry])
 const lookup=new Map(resolved.map(i=>[identity(i),i])),shown=items.map(i=>lookup.get(i.item_id)).filter(Boolean),missing=items.filter(i=>!lookup.has(i.item_id)),savedKeys=new Set(items.map(i=>i.item_type+':'+i.item_id))
 const places=shown.filter(i=>!i.event_key),entertainment=shown.filter(i=>i.event_key),active=view==='places'?places:entertainment,activeMissing=missing.filter(i=>i.item_type===(view==='places'?'venue':'event'))
 return <section className="gtc-saved gt5-saved gtc-my-good-times"><header className="gtc-page-heading"><div><h1>My GOOD TIMES</h1><small>Your plans, saved places and saved entertainment live here.</small></div></header><div className="gtc-tabs" role="tablist" aria-label="My GOOD TIMES library"><button role="tab" aria-selected={view==='plans'} className={view==='plans'?'active':''} onClick={()=>setView('plans')}>Plans · {plans.length}</button><button role="tab" aria-selected={view==='places'} className={view==='places'?'active':''} onClick={()=>setView('places')}>Places · {items.filter(i=>i.item_type==='venue').length}</button><button role="tab" aria-selected={view==='entertainment'} className={view==='entertainment'?'active':''} onClick={()=>setView('entertainment')}>Entertainment · {items.filter(i=>i.item_type==='event').length}</button></div>
 {view==='plans'?(plans.length?<div className="gtc-plan-grid">{plans.map(p=><button className="gtc-plan-tile" key={p.id} onClick={()=>onPlan(p)}><small>{displayDate(p.itinerary_date)} · {list(p.stops).length} stops</small><h2>{p.name}</h2><ol>{list(p.stops).slice(0,3).map((s,i)=><li key={s.id||i}>{s.name}</li>)}</ol><strong>Open plan ↗</strong></button>)}</div>:<State title="Your first plan starts here" action={<button onClick={onBuild}>Build My Night</button>}/>):<>{error&&<State error title="Some saved details are unavailable" body={error} action={<button onClick={()=>setRetry(x=>x+1)}>Retry</button>}/>}<CollectionGrid items={active} {...{savedKeys,onEvent,onVenue,onSave}}/>{activeMissing.map(i=><div className="gtc-unavailable" key={i.id}><div><strong>Saved {i.item_type} unavailable</strong><p>It may have ended or need a new verification. Your bookmark has not been deleted.</p></div><button onClick={()=>onSave(i.item_type,i.item_id)}>Remove bookmark</button></div>)}{!active.length&&!activeMissing.length&&<State title={view==='places'?'Save places worth returning to':'Save entertainment worth planning around'} action={<button onClick={view==='places'?onExplore:(onEntertainment||onExplore)}>{view==='places'?'Explore Places':'Explore Entertainment'}</button>}/>}</>}
 </section>
}

