import React,{useEffect,useRef,useState} from 'react'
import {MOODS,normalizePlanInput,editStops,venueFits} from './planner.js'
import {selectedCityClock,dateNumber} from '../good-times-event-clock.js'
import {list,displayDate,displayTime,identity,validStopStatus,itineraryWarnings,planText,downloadCalendar,safeLink,shiftDate} from './model.js'
import {State,Picture,ActionLink} from './Cards.jsx'
import {CollectionGrid} from './Collections.jsx'
import ShakeRestaurantPanel from '../ShakeRestaurantPanel.jsx'
import {persistPlan} from './account.js'
import {gtAssetUrl} from '../good-times-assets.js'
import {useDialogFocus} from './Details.jsx'
import {useBrowse} from './useBrowse.js'
import {loadExplorePage} from '../../intelligence/client.js'
import {shareContent} from '../../../native.js'
import {refreshStoredSession} from '../../../gt-auth-session.js'
const MOOD_ART={nightlife:'/venues/opium.jpg',chill:'/reference-base/atlanta-rooftop.webp',date:'/good-times-backgrounds/gt-cat-mood-date.webp',music:'/good-times-backgrounds/gt-cat-music.webp',food:'/good-times-backgrounds/gt-cat-dining.webp',sports:'/good-times-backgrounds/gt-cat-sports.webp',culture:'/good-times-backgrounds/gt-cat-culture.webp',rooftop:'/reference-base/atlanta-rooftop.webp'}
const RECENT_PLAN_KEY='gt_recent_plan_venue_ids'
const recentPlanIds=()=>{try{const rows=JSON.parse(localStorage.getItem(RECENT_PLAN_KEY)||'[]');return Array.isArray(rows)?rows.filter(Boolean).slice(0,20):[]}catch{return[]}}
const rememberPlanIds=plan=>{try{const next=[...(plan?.stops||[]).filter(s=>s?.type==='venue').map(s=>s.object_id||String(s.id||'').replace(/^venue:/,'')),...recentPlanIds()];localStorage.setItem(RECENT_PLAN_KEY,JSON.stringify([...new Set(next.filter(Boolean))].slice(0,20)))}catch{}}
const blank=()=>{const c=selectedCityClock('atlanta');const tomorrow=c.minute>=22*60;const next=Math.min(23*60,Math.max(19*60,Math.ceil((c.minute+30)/30)*30));return {date:tomorrow?shiftDate(c.date,1):c.date,start:tomorrow?'19:00':String(Math.floor(next/60)).padStart(2,'0')+':'+String(next%60).padStart(2,'0'),end:'01:00',people:2,vibes:['nightlife'],area:'',budget:'',adultOnly:false,allowUnknownHours:true}}
export default function Planner({session,venues,savedKeys,onEvent,onVenue,onSave,onGenerated,anchor,onClearAnchor,onAsk,askText,onAskText,askBusy,askResult,askMessage}){
 const [mode,setMode]=useState('guided'),[step,setStep]=useState(0),[values,setValues]=useState(()=>{try{const v=JSON.parse(localStorage.getItem('gt_plan_draft:'+session?.user?.id)||'null');return v&&v.date>=selectedCityClock('atlanta').date?{...blank(),...v}:blank()}catch{return blank()}}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[conflicts,setConflicts]=useState([]),requestId=useRef(null),abort=useRef(null)
 useEffect(()=>()=>abort.current?.abort(),[])
 useEffect(()=>{if(!session?.user?.id)return;try{localStorage.setItem('gt_plan_draft:'+session.user.id,JSON.stringify(values))}catch{}},[values,session?.user?.id])
 useEffect(()=>{if(anchor){setMode('guided');setStep(0);setValues(v=>({...v,anchorId:anchor.event_key||`venue:${anchor.id}`,date:anchor.event_date||v.date}));requestId.current=null}},[anchor])
 const change=patch=>{setValues(v=>({...v,...patch}));requestId.current=null;setError('');setConflicts([])}
 const toggle=id=>change({vibes:values.vibes.includes(id)?values.vibes.filter(v=>v!==id):[...values.vibes,id].slice(0,4)})
 const next=()=>{try{if(step===1)normalizePlanInput(values);if(step===0&&!values.vibes.length)throw new Error('Choose at least one vibe.');setStep(x=>Math.min(3,x+1));setError('')}catch(e){setError(e.message)}}
 const generate=async()=>{if(busy)return;setError('');setConflicts([]);try{normalizePlanInput(values);setBusy(true);requestId.current ||= crypto.randomUUID();let active=(await refreshStoredSession().catch(()=>({session:null})))?.session||session;if(!active?.access_token)throw new Error('Please sign in to build a plan.');const controller=new AbortController();abort.current=controller;const timer=setTimeout(()=>controller.abort(),18000);const payload={...values,requestId:requestId.current,avoidIds:recentPlanIds()};const post=token=>fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(payload),signal:controller.signal});let response;try{response=await post(active.access_token);if(response.status===401){const refreshed=await refreshStoredSession().catch(()=>({session:null}));active=refreshed?.session||null;if(active?.access_token&&active.access_token!==session?.access_token)response=await post(active.access_token)}}finally{clearTimeout(timer)}const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error||'Could not build the plan.');if(!body.plan){setConflicts(body.conflicts||['No matching route was found.']);requestId.current=null;return}rememberPlanIds(body.plan);requestId.current=null;onGenerated(body.plan)}catch(e){setError(e.name==='AbortError'?'The plan took too long. Retry; no booking was submitted.':e.message)}finally{setBusy(false)}}
 return <section className="gtc-planner gt5-plan"><header className="gtc-page-heading"><div><h1>Make it a good night.</h1><small>Three ways to find your next move.</small></div></header><nav className="gtc-tabs" aria-label="Planning methods">{[['guided','Build My Night'],['shake','Shake'],['ask','Ask']].map(([id,label])=><button className={mode===id?'active':''} aria-pressed={mode===id} onClick={()=>setMode(id)} key={id}>{label}</button>)}</nav>
 {mode==='guided'&&<>
 {anchor&&<div className="gtc-anchor"><span>Include <strong>{anchor.title||anchor.name}</strong></span><button onClick={()=>{onClearAnchor();change({anchorId:null})}}>Remove</button></div>}
 <ol className="gtc-progress" aria-label="Build My Night steps">{['Vibe','Basics','Preferences','Review'].map((s,i)=><li key={s}><button onClick={()=>setStep(i)} aria-current={i===step?'step':undefined} className={step===i?'active':''}><b>{i+1}</b>{s}</button></li>)}</ol>
 {step===0&&<><h2>What’s the vibe?</h2><p className="gtc-note">Pick up to four. Your lead choice comes first.</p><div className="gtc-mood-grid">{MOODS.map(([id,label,desc])=><button key={id} aria-pressed={values.vibes.includes(id)} className={values.vibes.includes(id)?'active':''} onClick={()=>toggle(id)}><Picture illustration src={MOOD_ART[id]?.startsWith('/good-times-backgrounds/')?gtAssetUrl(MOOD_ART[id].split('/').at(-1),'good-times-backgrounds'):MOOD_ART[id]} kind={label}/><span><strong>{label}</strong><small>{desc}</small></span><b aria-hidden="true">{values.vibes.includes(id)?'✓':'＋'}</b></button>)}</div>{values.vibes.length>1&&<label className="gtc-lead">Lead vibe<select value={values.vibes[0]} onChange={e=>change({vibes:[e.target.value,...values.vibes.filter(v=>v!==e.target.value)]})}>{values.vibes.map(v=><option key={v} value={v}>{MOODS.find(x=>x[0]===v)?.[1]}</option>)}</select></label>}</>}
 {step===1&&<><h2>Set the time and company.</h2><div className="gtc-form"><label>Date<input type="date" min={selectedCityClock('atlanta').date} value={values.date} onChange={e=>change({date:e.target.value})}/></label><label>People<input type="number" min="1" max="20" value={values.people} onChange={e=>change({people:e.target.value})}/></label><label>Start<input type="time" value={values.start} onChange={e=>change({start:e.target.value})}/></label><label>Finish<input type="time" value={values.end} onChange={e=>change({end:e.target.value})}/></label></div><p className="gtc-note">Times are Atlanta local time. A finish earlier than the start means the following morning.</p></>}
 {step===2&&<><h2>Make it your kind of night.</h2><div className="gtc-form"><label>Neighborhood<select value={values.area} onChange={e=>change({area:e.target.value})}><option value="">Any Atlanta area</option>{['Midtown','West Midtown','Buckhead','Downtown','Old Fourth Ward','East Atlanta'].map(a=><option key={a}>{a}</option>)}</select></label><label>Price band<select value={values.budget} onChange={e=>change({budget:e.target.value})}><option value="">No preference</option>{['$','$$','$$$','$$$$'].map(b=><option key={b}>{b}</option>)}</select></label></div><label className="gtc-check"><input type="checkbox" checked={values.adultOnly} onChange={e=>change({adultOnly:e.target.checked})}/>Everyone in the group is 21 or older.</label><label className="gtc-check"><input type="checkbox" checked={values.allowUnknownHours} onChange={e=>change({allowUnknownHours:e.target.checked})}/>Include strong places whose hours still need confirmation.</label><p className="gtc-note">Price bands are not fixed per-person budgets. Entry rules, availability, kitchen hours and travel need confirmation before booking.</p></>}
 {step===3&&<><h2>Review before we build.</h2><div className="gtc-review">{[['Vibes',values.vibes.map(v=>MOODS.find(x=>x[0]===v)?.[1]).join(' · '),0],['When',`${displayDate(values.date)} · ${displayTime(values.start)} – ${displayTime(values.end)}`,1],['Group',`${values.people} people`,1],['Area / price',`${values.area||'Atlanta'} · ${values.budget||'No preference'}`,2],['Unconfirmed hours',values.allowUnknownHours?'Allowed, clearly flagged':'Exclude from plan',2]].map(([label,value,s])=><button key={label} onClick={()=>setStep(s)}><span><small>{label}</small><strong>{value}</strong></span><span>Edit</span></button>)}</div><p className="gtc-note">Build creates suggestions, not reservations. Nothing is saved until you choose Save plan.</p></>}
 {error&&<State error title="Check your plan" body={error}/>} {!!conflicts.length&&<State title="A change is needed" body={conflicts.join(' ')} action={<button onClick={()=>setStep(2)}>Adjust preferences</button>}/>}
 <div className="gtc-builder-actions"><button disabled={step===0||busy} onClick={()=>setStep(x=>x-1)}>Back</button><button className="primary" disabled={busy} onClick={step<3?next:generate}>{busy?'Finding verified options…':step<3?'Continue →':'Build my plan'}</button></div>
 </>}
 {mode==='shake'&&<ShakeRestaurantPanel city="atlanta" cityName="Atlanta" session={session} venues={venues} onOpen={onVenue} onBuild={v=>{setMode('guided');setValues(x=>({...x,anchorId:`venue:${v.id}`}));setStep(0)}}/>}
 {mode==='ask'&&<><h2>What are you in the mood for?</h2><label className="gtc-ask-label">Ask GOOD TIMES<textarea value={askText} onChange={e=>onAskText(e.target.value)} placeholder="A low-key date night in Midtown with live music…" maxLength={2000}/></label><button className="gtc-primary" disabled={askBusy||!askText.trim()} onClick={()=>onAsk(askText,'recommend')}>{askBusy?'Checking current options…':'Find my options'}</button>{askMessage&&<p role="status" className="gtc-note">{askMessage}</p>}{askResult&&<CollectionGrid items={[...list(askResult.events),...list(askResult.venues)]} {...{savedKeys,onEvent,onVenue,onSave}}/>}<p className="gtc-note">Choose an option to plan around it. No automatic purchases or reservations.</p></>}
 </section>
}
export function Itinerary({plan,session,existing,onClose,onSaved,onSwap}){
 const modalRef=useRef(null);const [draft,setDraft]=useState(plan),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[hasSaved,setHasSaved]=useState(existing),[swap,setSwap]=useState(null)
 useDialogFocus(modalRef,()=>{if(!dirty||window.confirm('Leave without saving these changes?'))onClose()})
 useEffect(()=>{setDraft(plan);setDirty(false);setError('');setHasSaved(existing)},[plan.id])
 const edit=(action,i,value)=>{try{const next=editStops(draft,action,i,value);setDraft(next);setDirty(true);setError('');setNotice('Changes are not saved yet.')}catch(e){setError(e.message)}}
 const save=async()=>{if(busy)return;setBusy(true);setError('');try{const row=await persistPlan(draft,session,{existing:hasSaved});setDraft(row);setDirty(false);setHasSaved(true);setNotice('Plan saved.');onSaved(row)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const warnings=[...new Set([...list(draft.metadata?.warnings),...itineraryWarnings(draft)])]
 return <div className="gt5-overlay gtc-overlay" role="dialog" aria-modal="true" aria-label="Your GOOD TIMES itinerary" ref={modalRef}><article className="gt5-itinerary gtc-itinerary"><header className="gtc-detail-toolbar"><button type="button" className="gtc-itinerary-back" aria-label="Close itinerary" onClick={event=>{event.preventDefault();event.stopPropagation();if(!dirty||window.confirm('Leave without saving these changes?'))onClose()}}>← Back</button><span>{hasSaved?'Saved plan':'Unsaved suggestions'}</span></header><div className="gtc-detail-copy"><input aria-label="Plan name" className="gtc-plan-name" value={draft.name||''} onChange={e=>{setDraft(x=>({...x,name:e.target.value}));setDirty(true)}} maxLength={120}/><p>{displayDate(draft.itinerary_date)} · Atlanta · {draft.group_size||2} people</p><p className="gtc-note">Suggested arrivals—not confirmed bookings.</p>
 {error&&<State error title="Could not update plan" body={error}/>} {notice&&<p role="status" className="gtc-note">{notice}</p>}
 <div className="gtc-timeline">{list(draft.stops).map((s,i)=><section key={s.id||i} className="gtc-stop"><header><b>{i+1}</b><span><strong>{displayTime(s.time)}</strong><small>{s.date&&s.date!==draft.itinerary_date?displayDate(s.date):s.time_basis==='published_start'?'Published start':'Suggested arrival'}</small></span><button aria-pressed={!!s.locked} onClick={()=>edit('lock',i)}>{s.locked?'Unlock':'Lock'}</button></header><div className="gtc-stop-body"><Picture src={s.image_url||s.image} kind={s.type==='event'?'Event':'Place'}/><div><h2>{s.name}</h2><p>{s.venue||s.neighborhood}</p><small>{validStopStatus(s)}</small><ActionLink href={s.ticket_url||s.booking_link||s.website}>{s.ticket_url?'View tickets':'Check details & availability'}</ActionLink></div></div><div className="gtc-stop-actions"><button disabled={!!s.locked||i===0} onClick={()=>edit('up',i)}>Move up</button><button disabled={!!s.locked||i===draft.stops.length-1} onClick={()=>edit('down',i)}>Move down</button><button disabled={!!s.locked} onClick={()=>setSwap(i)}>Swap</button><button disabled={!!s.locked} onClick={()=>edit('remove',i)}>Remove</button>{s.type==='venue'&&<label>Arrival<input type="time" disabled={!!s.locked} value={s.time||''} onChange={e=>edit('time',i,e.target.value)}/></label>}</div></section>)}</div>
 {!draft.stops.length&&<State title="This plan has no stops" body="Close this plan and choose another experience before saving."/>}
 {swap!==null&&<SwapStop plan={draft} index={swap} onClose={()=>setSwap(null)} onReplace={stop=>{setDraft(p=>({...p,stops:p.stops.map((s,i)=>i===swap?stop:s)}));setDirty(true);setSwap(null);setNotice('Stop replaced. Check timing and save your changes.')}}/>}
 {!!warnings.length&&<details className="gtc-warnings"><summary>Before you go · {warnings.length} checks</summary>{warnings.map(w=><p key={w}>{w}</p>)}</details>}
 <div className="gtc-itinerary-actions"><button className="primary" disabled={busy||!draft.stops.length} onClick={save}>{busy?'Saving…':hasSaved?'Save changes':'Save plan'}</button><button onClick={async()=>{const ok=await shareContent({title:draft.name,text:planText(draft),dialogTitle:'Share plan details'});setNotice(ok?'Plan details shared. No private link was published.':'Sharing was cancelled or unavailable.')}}>Share details</button><button disabled={!draft.stops.length} onClick={()=>downloadCalendar(draft)}>Add to calendar</button></div>
 </div></article></div>
}

function SwapStop({plan,index,onReplace,onClose}){
 const [rows,setRows]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[retry,setRetry]=useState(0)
 useEffect(()=>{const c=new AbortController(),timer=setTimeout(()=>{setBusy(true);loadExplorePage('Atlanta',{query,limit:12,sort:'quality'},{signal:c.signal}).then(r=>{setRows(r.items.filter(v=>!plan.stops.some(s=>s.id===`venue:${v.id}`)));setError('')}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setBusy(false)})},240);return()=>{clearTimeout(timer);c.abort()}},[query,retry])
 const choose=async v=>{setBusy(true);setError('');try{const r=await fetch('/api/browse?'+new URLSearchParams({kind:'venue',id:v.id}),{signal:AbortSignal.timeout(9000)}),b=await r.json(),full=b.items?.[0];if(!r.ok||!full)throw new Error('This place is no longer verified. Choose another.');const old=plan.stops[index],prefs=normalizePlanInput({...plan.vibe_profile,date:plan.itinerary_date}),arrival=(dateNumber(old.date||plan.itinerary_date)-dateNumber(plan.itinerary_date))*1440+Number(old.time?.slice(0,2))*60+Number(old.time?.slice(3,5));const fit=venueFits(full,prefs,arrival);if(!fit.fits)throw new Error('This place does not fit your saved constraints or hours. Change preferences before replacing it.');onReplace({id:`venue:${full.id}`,object_id:full.id,type:'venue',name:full.name,role:old.role,date:old.date||plan.itinerary_date,time:old.time,time_basis:'suggested_arrival',venue:full.name,address:full.address,neighborhood:full.neighborhood,image_url:full.hero_image,website:safeLink(full.website),booking_link:safeLink(full.booking_link),status:'SUGGESTED',hours_verified:fit.verified===true,travel_verified:false})}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="gtc-swap" aria-label="Swap selected stop"><header><h2>Replace {plan.stops[index]?.name}</h2><button onClick={onClose}>Cancel</button></header><div className="gtc-search"><input aria-label="Find replacement place" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a replacement place…"/></div>{error&&<State error title="Check this replacement" body={error} action={<button onClick={()=>setRetry(x=>x+1)}>Retry</button>}/>}<div className="gtc-swap-choices">{rows.map(v=><button key={v.id} disabled={busy} onClick={()=>choose(v)}><strong>{v.name}</strong><small>{v.neighborhood||'Atlanta'}</small></button>)}</div>{busy&&<p role="status">Checking current places…</p>}</section>
}
