/** Existing registered ESPN source, on demand only. No ingestion, polling or database mutation. */
import {dateNumber,selectedCityClock} from '../src/features/experience/good-times-event-clock.js'
import {safeLink,shiftDate} from '../src/features/experience/complete/model.js'
const FEEDS=Object.freeze({NFL:{path:'football/nfl',teams:['Atlanta Falcons']},NBA:{path:'basketball/nba',teams:['Atlanta Hawks']},MLB:{path:'baseball/mlb',teams:['Atlanta Braves']},WNBA:{path:'basketball/wnba',teams:['Atlanta Dream']},MLS:{path:'soccer/usa.1',teams:['Atlanta United FC','Atlanta United']}})
const cache=new Map(),inflight=new Map()
export function sportsScope(url,now=Date.now()){const p=new URL(url,'https://thegoodtimesworldwide.com').searchParams,c=selectedCityClock('atlanta',now),date=p.get('date')||c.date,league=p.get('league')||'All';if(dateNumber(date)===null||Math.abs(dateNumber(date)-dateNumber(c.date))>180)throw new Error('Choose a date within six months.');if(league!=='All'&&!FEEDS[league])throw new Error('Unknown league.');return {date,to:shiftDate(date,7),leagues:league==='All'?Object.keys(FEEDS):[league]}}
function localParts(value){const d=new Date(value);if(!Number.isFinite(d.getTime()))return null;const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).map(x=>[x.type,x.value]));return {date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`}}
export function mapGames(payload,league,scope,now=Date.now()) {
 if(!Array.isArray(payload?.events))throw new Error('FORMAT');const conf=FEEDS[league]
 return payload.events.flatMap(e=>{const c=e.competitions?.[0],teams=c?.competitors||[],home=teams.find(t=>t.homeAway==='home'),away=teams.find(t=>t.homeAway==='away');if(!e.id||!home?.team||!away?.team)return [];const homeLocal=conf.teams.includes(home.team.displayName),awayLocal=conf.teams.includes(away.team.displayName);if(!homeLocal&&!awayLocal)return [];const when=localParts(c.date||e.date);if(!when||when.date<scope.date||when.date>scope.to)return [];const st=c.status||e.status||{},type=st.type||{},state=type.state,cancelled=/CANCEL/.test(type.name||''),postponed=/POSTPON/.test(type.name||'');const score=x=>x!==''&&x!=null&&Number.isFinite(Number(x))?Number(x):null;const hasScores=!cancelled&&!postponed&&['in','post'].includes(state)&&score(home.score)!==null&&score(away.score)!==null;return [{id:`espn:${league}:${e.id}`,league,home_team:home.team.displayName,home_abbr:home.team.abbreviation,away_team:away.team.displayName,away_abbr:away.team.abbreviation,game_date:when.date,game_time:when.time,venue:c.venue?.fullName||null,city_key:'atlanta',is_home_game:homeLocal,status:cancelled?'cancelled':postponed?'postponed':state==='in'?'live':state==='post'?'final':'scheduled',status_detail:String(type.shortDetail||type.detail||'').slice(0,120),home_score:hasScores?score(home.score):null,away_score:hasScores?score(away.score):null,home_logo:safeLink(home.team.logo),away_logo:safeLink(away.team.logo),source_url:safeLink(e.links?.find(l=>l.rel?.includes('summary'))?.href||e.links?.[0]?.href),source_name:'ESPN',updated_at:new Date(now).toISOString(),source_timestamp_kind:'fetched_at',score_is_provider_reported:hasScores}]})
}
export async function sportsLive(url,{fetcher=globalThis.fetch,now=Date.now(),useCache=true}={}) {
 const scope=sportsScope(url,now),key=JSON.stringify(scope),existing=cache.get(key);if(useCache&&existing&&now-existing.at<30000)return existing.value;if(useCache&&inflight.has(key))return inflight.get(key)
 const request=(async()=>{const results=await Promise.all(scope.leagues.map(async league=>{const conf=FEEDS[league],u=new URL(`https://site.api.espn.com/apis/site/v2/sports/${conf.path}/scoreboard`);u.searchParams.set('dates',scope.date.replaceAll('-','')+'-'+scope.to.replaceAll('-',''));u.searchParams.set('limit','100');let httpStatus=null;try{const r=await fetcher(u.toString(),{headers:{Accept:'application/json'},signal:AbortSignal.timeout(5000)});httpStatus=r.status;if(!r.ok)return {league,items:[],ok:false,httpStatus,errorClass:'HTTP'};const body=await r.json();return {league,items:mapGames(body,league,scope,now),ok:true,httpStatus}}catch(e){return {league,items:[],ok:false,httpStatus,errorClass:e.message==='FORMAT'?'FORMAT':e.name==='TimeoutError'||e.name==='AbortError'?'TIMEOUT':e.name==='SyntaxError'?'JSON':'NETWORK_OR_MAPPING'}}}));const failed=results.filter(r=>!r.ok).map(r=>r.league);const value={ok:failed.length!==scope.leagues.length,items:results.flatMap(r=>r.items).sort((a,b)=>a.game_date.localeCompare(b.game_date)||a.game_time.localeCompare(b.game_time)),nextCursor:null,countType:'returned',asOf:new Date(now).toISOString(),scope,source:'ESPN',failedLeagues:failed,diagnostics:results.map(({league,ok,httpStatus,errorClass})=>({league,ok,httpStatus,errorClass})),partial:failed.length>0,notice:failed.length?`${failed.join(', ')} could not refresh. Other available leagues remain visible.`:'Provider-reported scores; refreshed on opening or manual refresh.'};if(value.ok&&useCache){if(cache.size>40)cache.clear();cache.set(key,{at:now,value})}return value})();if(useCache)inflight.set(key,request);try{return await request}finally{inflight.delete(key)}
}
export default async function handler(req,res){res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');if(req.method!=='GET'){res.statusCode=405;res.setHeader('Allow','GET');return res.end(JSON.stringify({ok:false,error:'Read-only sports endpoint.'}))}try{const data=await sportsLive(req.url);res.statusCode=data.ok?200:503;res.end(JSON.stringify(data.ok?data:{...data,error:'Sports provider unavailable. Use official schedules or retry.'}))}catch(e){res.statusCode=400;res.end(JSON.stringify({ok:false,error:e.message}))}}
